// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv1DMac_new417 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [31:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg in_V_V_read;
reg out_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [13:0] weights17_m_weights_3_address0;
reg    weights17_m_weights_3_ce0;
wire   [5:0] weights17_m_weights_3_q0;
wire   [13:0] weights17_m_weights_2_address0;
reg    weights17_m_weights_2_ce0;
wire   [5:0] weights17_m_weights_2_q0;
wire   [13:0] weights17_m_weights_1_address0;
reg    weights17_m_weights_1_ce0;
wire   [5:0] weights17_m_weights_1_q0;
wire   [13:0] weights17_m_weights_s_address0;
reg    weights17_m_weights_s_ce0;
wire   [5:0] weights17_m_weights_s_q0;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_flatten6_reg_1479;
reg   [0:0] exitcond_flatten6_reg_1479_pp0_iter1_reg;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] tmp_111_reg_1506;
reg   [0:0] tmp_111_reg_1506_pp0_iter3_reg;
reg   [20:0] indvar_flatten6_reg_243;
reg   [15:0] indvar_flatten_reg_254;
reg   [6:0] nm_reg_265;
reg   [8:0] sf_reg_276;
wire   [0:0] exitcond_flatten6_fu_319_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [20:0] indvar_flatten_next6_fu_325_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] nm_t_mid2_fu_419_p3;
reg   [5:0] nm_t_mid2_reg_1488;
reg   [5:0] nm_t_mid2_reg_1488_pp0_iter1_reg;
reg   [5:0] nm_t_mid2_reg_1488_pp0_iter2_reg;
wire   [6:0] nm_mid2_fu_427_p3;
wire   [13:0] tmp_106_fu_439_p2;
reg   [13:0] tmp_106_reg_1501;
wire   [0:0] tmp_111_fu_445_p2;
reg   [0:0] tmp_111_reg_1506_pp0_iter1_reg;
reg   [0:0] tmp_111_reg_1506_pp0_iter2_reg;
wire   [8:0] sf_1_fu_451_p2;
wire   [15:0] indvar_flatten_next_fu_463_p3;
reg   [6:0] tmp_67_reg_1540;
reg   [0:0] tmp_926_reg_1545;
wire   [0:0] tmp_108_fu_546_p2;
reg   [0:0] tmp_108_reg_1550;
reg   [6:0] tmp_70_reg_1555;
reg   [0:0] tmp_929_reg_1560;
wire   [0:0] tmp_255_1_fu_616_p2;
reg   [0:0] tmp_255_1_reg_1565;
reg   [6:0] tmp_73_reg_1570;
reg   [0:0] tmp_932_reg_1575;
wire   [0:0] tmp_255_2_fu_686_p2;
reg   [0:0] tmp_255_2_reg_1580;
reg   [6:0] tmp_76_reg_1585;
reg   [0:0] tmp_935_reg_1590;
wire   [0:0] tmp_255_3_fu_756_p2;
reg   [0:0] tmp_255_3_reg_1595;
wire   [7:0] p_Val2_7_fu_1019_p2;
reg   [7:0] p_Val2_7_reg_1600;
wire   [7:0] p_Val2_21_1_fu_1158_p2;
reg   [7:0] p_Val2_21_1_reg_1605;
wire   [7:0] p_Val2_21_2_fu_1297_p2;
reg   [7:0] p_Val2_21_2_reg_1610;
wire   [7:0] p_Val2_21_3_fu_1436_p2;
reg   [7:0] p_Val2_21_3_reg_1615;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
wire   [63:0] tmp_107_fu_471_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] macRegisters_0_V_2_fu_162;
wire   [7:0] macRegisters_0_V_fu_791_p2;
reg   [7:0] macRegisters_1_V_2_fu_166;
wire   [7:0] macRegisters_1_V_fu_814_p2;
reg   [7:0] macRegisters_2_V_2_fu_170;
wire   [7:0] macRegisters_2_V_fu_837_p2;
reg   [7:0] macRegisters_3_V_2_fu_174;
wire   [7:0] macRegisters_3_V_fu_860_p2;
wire   [5:0] tmp_fu_307_p1;
wire   [0:0] exitcond_flatten_fu_331_p2;
wire   [13:0] tmp_s_fu_311_p3;
wire   [0:0] tmp_882_fu_367_p2;
wire   [0:0] not_exitcond_flatten_fu_361_p2;
wire   [6:0] nm_mid_fu_337_p3;
wire   [0:0] tmp_108_mid_fu_373_p2;
wire   [0:0] tmp_853_fu_385_p2;
wire   [6:0] nm_1_fu_379_p2;
wire   [5:0] tmp_924_fu_399_p1;
wire   [13:0] tmp_107_mid1_fu_403_p3;
wire   [13:0] tmp_107_mid_fu_345_p3;
wire   [5:0] nm_t_mid_fu_353_p3;
wire   [8:0] sf_mid2_fu_391_p3;
wire   [13:0] sf_cast1_fu_435_p1;
wire   [13:0] tmp_107_mid2_fu_411_p3;
wire   [15:0] indvar_flatten_op_fu_457_p2;
wire  signed [5:0] p_Val2_s_fu_486_p0;
wire  signed [7:0] p_Val2_s_fu_486_p1;
wire  signed [13:0] p_08_cast_cast_fu_478_p1;
wire   [13:0] p_Val2_s_fu_486_p2;
wire   [0:0] tmp_927_fu_518_p1;
wire   [0:0] tmp_925_fu_492_p3;
wire   [4:0] tmp_93_fu_528_p4;
wire   [0:0] tmp_92_fu_522_p2;
wire   [5:0] tmp_94_fu_538_p3;
wire  signed [5:0] p_Val2_1_fu_556_p0;
wire  signed [7:0] p_Val2_1_fu_556_p1;
wire   [13:0] p_Val2_1_fu_556_p2;
wire   [0:0] tmp_930_fu_588_p1;
wire   [0:0] tmp_928_fu_562_p3;
wire   [4:0] tmp_97_fu_598_p4;
wire   [0:0] tmp_96_fu_592_p2;
wire   [5:0] tmp_98_fu_608_p3;
wire  signed [5:0] p_Val2_2_fu_626_p0;
wire  signed [7:0] p_Val2_2_fu_626_p1;
wire   [13:0] p_Val2_2_fu_626_p2;
wire   [0:0] tmp_933_fu_658_p1;
wire   [0:0] tmp_931_fu_632_p3;
wire   [4:0] tmp_101_fu_668_p4;
wire   [0:0] tmp_100_fu_662_p2;
wire   [5:0] tmp_102_fu_678_p3;
wire  signed [5:0] p_Val2_3_fu_696_p0;
wire  signed [7:0] p_Val2_3_fu_696_p1;
wire   [13:0] p_Val2_3_fu_696_p2;
wire   [0:0] tmp_936_fu_728_p1;
wire   [0:0] tmp_934_fu_702_p3;
wire   [4:0] tmp_105_fu_738_p4;
wire   [0:0] tmp_104_fu_732_p2;
wire   [5:0] tmp_110_fu_748_p3;
wire   [0:0] qb_assign_1_fu_777_p2;
wire   [7:0] tmp_109_fu_781_p1;
wire  signed [7:0] tmp_68_fu_774_p1;
wire   [7:0] tmp1_fu_785_p2;
wire   [0:0] qb_assign_1_1_fu_800_p2;
wire   [7:0] tmp_256_1_fu_804_p1;
wire  signed [7:0] tmp_71_fu_797_p1;
wire   [7:0] tmp2_fu_808_p2;
wire   [0:0] qb_assign_1_2_fu_823_p2;
wire   [7:0] tmp_256_2_fu_827_p1;
wire  signed [7:0] tmp_74_fu_820_p1;
wire   [7:0] tmp3_fu_831_p2;
wire   [0:0] qb_assign_1_3_fu_846_p2;
wire   [7:0] tmp_256_3_fu_850_p1;
wire  signed [7:0] tmp_77_fu_843_p1;
wire   [7:0] tmp4_fu_854_p2;
wire   [7:0] tmp_78_fu_886_p66;
wire   [7:0] tmp_79_fu_1025_p66;
wire   [7:0] tmp_80_fu_1164_p66;
wire   [7:0] tmp_81_fu_1303_p66;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Conv1DMac_new417_0iy #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights17_m_weights_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights17_m_weights_3_address0),
    .ce0(weights17_m_weights_3_ce0),
    .q0(weights17_m_weights_3_q0)
);

Conv1DMac_new417_1iI #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights17_m_weights_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights17_m_weights_2_address0),
    .ce0(weights17_m_weights_2_ce0),
    .q0(weights17_m_weights_2_q0)
);

Conv1DMac_new417_2iS #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights17_m_weights_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights17_m_weights_1_address0),
    .ce0(weights17_m_weights_1_ce0),
    .q0(weights17_m_weights_1_q0)
);

Conv1DMac_new417_3i2 #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights17_m_weights_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights17_m_weights_s_address0),
    .ce0(weights17_m_weights_s_ce0),
    .q0(weights17_m_weights_s_q0)
);

computeS3_mux_646yd2_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_U148(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd249),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd4),
    .din8(8'd0),
    .din9(8'd0),
    .din10(8'd7),
    .din11(8'd0),
    .din12(8'd0),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd0),
    .din18(8'd255),
    .din19(8'd0),
    .din20(8'd2),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd18),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd21),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd1),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd255),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd249),
    .din52(8'd0),
    .din53(8'd255),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd249),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd4),
    .din64(nm_t_mid2_reg_1488_pp0_iter2_reg),
    .dout(tmp_78_fu_886_p66)
);

computeS3_mux_646yd2_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_U149(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd0),
    .din9(8'd1),
    .din10(8'd8),
    .din11(8'd0),
    .din12(8'd0),
    .din13(8'd0),
    .din14(8'd247),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd5),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd2),
    .din31(8'd0),
    .din32(8'd5),
    .din33(8'd18),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd255),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd1),
    .din51(8'd13),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd1),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd20),
    .din64(nm_t_mid2_reg_1488_pp0_iter2_reg),
    .dout(tmp_79_fu_1025_p66)
);

computeS3_mux_646yd2_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_U150(
    .din0(8'd3),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd5),
    .din9(8'd0),
    .din10(8'd255),
    .din11(8'd8),
    .din12(8'd5),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd2),
    .din25(8'd0),
    .din26(8'd255),
    .din27(8'd253),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd11),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd2),
    .din46(8'd1),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd20),
    .din54(8'd1),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1488_pp0_iter2_reg),
    .dout(tmp_80_fu_1164_p66)
);

computeS3_mux_646yd2_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_U151(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd255),
    .din5(8'd10),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd0),
    .din9(8'd0),
    .din10(8'd254),
    .din11(8'd0),
    .din12(8'd0),
    .din13(8'd20),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd13),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd2),
    .din28(8'd1),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd247),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd250),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd253),
    .din52(8'd0),
    .din53(8'd254),
    .din54(8'd1),
    .din55(8'd253),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1488_pp0_iter2_reg),
    .dout(tmp_81_fu_1303_p66)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten6_reg_243 <= indvar_flatten_next6_fu_325_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten6_reg_243 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_254 <= indvar_flatten_next_fu_463_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_254 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_111_reg_1506_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_0_V_2_fu_162 <= macRegisters_0_V_fu_791_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_111_reg_1506_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_0_V_2_fu_162 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_111_reg_1506_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_1_V_2_fu_166 <= macRegisters_1_V_fu_814_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_111_reg_1506_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_1_V_2_fu_166 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_111_reg_1506_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_2_V_2_fu_170 <= macRegisters_2_V_fu_837_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_111_reg_1506_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_2_V_2_fu_170 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_111_reg_1506_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_3_V_2_fu_174 <= macRegisters_3_V_fu_860_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_111_reg_1506_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_3_V_2_fu_174 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nm_reg_265 <= nm_mid2_fu_427_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nm_reg_265 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sf_reg_276 <= sf_1_fu_451_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sf_reg_276 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten6_reg_1479 <= exitcond_flatten6_fu_319_p2;
        exitcond_flatten6_reg_1479_pp0_iter1_reg <= exitcond_flatten6_reg_1479;
        nm_t_mid2_reg_1488_pp0_iter1_reg <= nm_t_mid2_reg_1488;
        tmp_111_reg_1506_pp0_iter1_reg <= tmp_111_reg_1506;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_fu_319_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nm_t_mid2_reg_1488 <= nm_t_mid2_fu_419_p3;
        tmp_106_reg_1501 <= tmp_106_fu_439_p2;
        tmp_111_reg_1506 <= tmp_111_fu_445_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        nm_t_mid2_reg_1488_pp0_iter2_reg <= nm_t_mid2_reg_1488_pp0_iter1_reg;
        tmp_111_reg_1506_pp0_iter2_reg <= tmp_111_reg_1506_pp0_iter1_reg;
        tmp_111_reg_1506_pp0_iter3_reg <= tmp_111_reg_1506_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_111_reg_1506_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_21_1_reg_1605 <= p_Val2_21_1_fu_1158_p2;
        p_Val2_21_2_reg_1610 <= p_Val2_21_2_fu_1297_p2;
        p_Val2_21_3_reg_1615 <= p_Val2_21_3_fu_1436_p2;
        p_Val2_7_reg_1600 <= p_Val2_7_fu_1019_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_108_reg_1550 <= tmp_108_fu_546_p2;
        tmp_255_1_reg_1565 <= tmp_255_1_fu_616_p2;
        tmp_255_2_reg_1580 <= tmp_255_2_fu_686_p2;
        tmp_255_3_reg_1595 <= tmp_255_3_fu_756_p2;
        tmp_67_reg_1540 <= {{p_Val2_s_fu_486_p2[13:7]}};
        tmp_70_reg_1555 <= {{p_Val2_1_fu_556_p2[13:7]}};
        tmp_73_reg_1570 <= {{p_Val2_2_fu_626_p2[13:7]}};
        tmp_76_reg_1585 <= {{p_Val2_3_fu_696_p2[13:7]}};
        tmp_926_reg_1545 <= p_Val2_s_fu_486_p2[32'd6];
        tmp_929_reg_1560 <= p_Val2_1_fu_556_p2[32'd6];
        tmp_932_reg_1575 <= p_Val2_2_fu_626_p2[32'd6];
        tmp_935_reg_1590 <= p_Val2_3_fu_696_p2[32'd6];
    end
end

always @ (*) begin
    if ((exitcond_flatten6_fu_319_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_111_reg_1506_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_111_reg_1506_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights17_m_weights_1_ce0 = 1'b1;
    end else begin
        weights17_m_weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights17_m_weights_2_ce0 = 1'b1;
    end else begin
        weights17_m_weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights17_m_weights_3_ce0 = 1'b1;
    end else begin
        weights17_m_weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights17_m_weights_s_ce0 = 1'b1;
    end else begin
        weights17_m_weights_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_flatten6_fu_319_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten6_fu_319_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((tmp_111_reg_1506_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_111_reg_1506_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_111_reg_1506_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((exitcond_flatten6_reg_1479_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = ((tmp_111_reg_1506_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign exitcond_flatten6_fu_319_p2 = ((indvar_flatten6_reg_243 == 21'd1048576) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_331_p2 = ((indvar_flatten_reg_254 == 16'd16384) ? 1'b1 : 1'b0);

assign indvar_flatten_next6_fu_325_p2 = (21'd1 + indvar_flatten6_reg_243);

assign indvar_flatten_next_fu_463_p3 = ((exitcond_flatten_fu_331_p2[0:0] === 1'b1) ? 16'd1 : indvar_flatten_op_fu_457_p2);

assign indvar_flatten_op_fu_457_p2 = (indvar_flatten_reg_254 + 16'd1);

assign macRegisters_0_V_fu_791_p2 = ($signed(tmp_68_fu_774_p1) + $signed(tmp1_fu_785_p2));

assign macRegisters_1_V_fu_814_p2 = ($signed(tmp_71_fu_797_p1) + $signed(tmp2_fu_808_p2));

assign macRegisters_2_V_fu_837_p2 = ($signed(tmp_74_fu_820_p1) + $signed(tmp3_fu_831_p2));

assign macRegisters_3_V_fu_860_p2 = ($signed(tmp_77_fu_843_p1) + $signed(tmp4_fu_854_p2));

assign nm_1_fu_379_p2 = (7'd1 + nm_mid_fu_337_p3);

assign nm_mid2_fu_427_p3 = ((tmp_108_mid_fu_373_p2[0:0] === 1'b1) ? nm_1_fu_379_p2 : nm_mid_fu_337_p3);

assign nm_mid_fu_337_p3 = ((exitcond_flatten_fu_331_p2[0:0] === 1'b1) ? 7'd0 : nm_reg_265);

assign nm_t_mid2_fu_419_p3 = ((tmp_108_mid_fu_373_p2[0:0] === 1'b1) ? tmp_924_fu_399_p1 : nm_t_mid_fu_353_p3);

assign nm_t_mid_fu_353_p3 = ((exitcond_flatten_fu_331_p2[0:0] === 1'b1) ? 6'd0 : tmp_fu_307_p1);

assign not_exitcond_flatten_fu_361_p2 = (exitcond_flatten_fu_331_p2 ^ 1'd1);

assign out_V_V_din = {{{{p_Val2_21_3_reg_1615}, {p_Val2_21_2_reg_1610}}, {p_Val2_21_1_reg_1605}}, {p_Val2_7_reg_1600}};

assign p_08_cast_cast_fu_478_p1 = $signed(in_V_V_dout);

assign p_Val2_1_fu_556_p0 = weights17_m_weights_2_q0;

assign p_Val2_1_fu_556_p1 = p_08_cast_cast_fu_478_p1;

assign p_Val2_1_fu_556_p2 = ($signed(p_Val2_1_fu_556_p0) * $signed(p_Val2_1_fu_556_p1));

assign p_Val2_21_1_fu_1158_p2 = (macRegisters_1_V_fu_814_p2 + tmp_79_fu_1025_p66);

assign p_Val2_21_2_fu_1297_p2 = (macRegisters_2_V_fu_837_p2 + tmp_80_fu_1164_p66);

assign p_Val2_21_3_fu_1436_p2 = (macRegisters_3_V_fu_860_p2 + tmp_81_fu_1303_p66);

assign p_Val2_2_fu_626_p0 = weights17_m_weights_1_q0;

assign p_Val2_2_fu_626_p1 = p_08_cast_cast_fu_478_p1;

assign p_Val2_2_fu_626_p2 = ($signed(p_Val2_2_fu_626_p0) * $signed(p_Val2_2_fu_626_p1));

assign p_Val2_3_fu_696_p0 = weights17_m_weights_s_q0;

assign p_Val2_3_fu_696_p1 = p_08_cast_cast_fu_478_p1;

assign p_Val2_3_fu_696_p2 = ($signed(p_Val2_3_fu_696_p0) * $signed(p_Val2_3_fu_696_p1));

assign p_Val2_7_fu_1019_p2 = (macRegisters_0_V_fu_791_p2 + tmp_78_fu_886_p66);

assign p_Val2_s_fu_486_p0 = weights17_m_weights_3_q0;

assign p_Val2_s_fu_486_p1 = p_08_cast_cast_fu_478_p1;

assign p_Val2_s_fu_486_p2 = ($signed(p_Val2_s_fu_486_p0) * $signed(p_Val2_s_fu_486_p1));

assign qb_assign_1_1_fu_800_p2 = (tmp_929_reg_1560 & tmp_255_1_reg_1565);

assign qb_assign_1_2_fu_823_p2 = (tmp_932_reg_1575 & tmp_255_2_reg_1580);

assign qb_assign_1_3_fu_846_p2 = (tmp_935_reg_1590 & tmp_255_3_reg_1595);

assign qb_assign_1_fu_777_p2 = (tmp_926_reg_1545 & tmp_108_reg_1550);

assign sf_1_fu_451_p2 = (sf_mid2_fu_391_p3 + 9'd1);

assign sf_cast1_fu_435_p1 = sf_mid2_fu_391_p3;

assign sf_mid2_fu_391_p3 = ((tmp_853_fu_385_p2[0:0] === 1'b1) ? 9'd0 : sf_reg_276);

assign start_out = real_start;

assign tmp1_fu_785_p2 = (tmp_109_fu_781_p1 + macRegisters_0_V_2_fu_162);

assign tmp2_fu_808_p2 = (tmp_256_1_fu_804_p1 + macRegisters_1_V_2_fu_166);

assign tmp3_fu_831_p2 = (tmp_256_2_fu_827_p1 + macRegisters_2_V_2_fu_170);

assign tmp4_fu_854_p2 = (tmp_256_3_fu_850_p1 + macRegisters_3_V_2_fu_174);

assign tmp_100_fu_662_p2 = (tmp_933_fu_658_p1 | tmp_931_fu_632_p3);

assign tmp_101_fu_668_p4 = {{p_Val2_2_fu_626_p2[5:1]}};

assign tmp_102_fu_678_p3 = {{tmp_101_fu_668_p4}, {tmp_100_fu_662_p2}};

assign tmp_104_fu_732_p2 = (tmp_936_fu_728_p1 | tmp_934_fu_702_p3);

assign tmp_105_fu_738_p4 = {{p_Val2_3_fu_696_p2[5:1]}};

assign tmp_106_fu_439_p2 = (sf_cast1_fu_435_p1 + tmp_107_mid2_fu_411_p3);

assign tmp_107_fu_471_p1 = tmp_106_reg_1501;

assign tmp_107_mid1_fu_403_p3 = {{tmp_924_fu_399_p1}, {8'd0}};

assign tmp_107_mid2_fu_411_p3 = ((tmp_108_mid_fu_373_p2[0:0] === 1'b1) ? tmp_107_mid1_fu_403_p3 : tmp_107_mid_fu_345_p3);

assign tmp_107_mid_fu_345_p3 = ((exitcond_flatten_fu_331_p2[0:0] === 1'b1) ? 14'd0 : tmp_s_fu_311_p3);

assign tmp_108_fu_546_p2 = ((tmp_94_fu_538_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_108_mid_fu_373_p2 = (tmp_882_fu_367_p2 & not_exitcond_flatten_fu_361_p2);

assign tmp_109_fu_781_p1 = qb_assign_1_fu_777_p2;

assign tmp_110_fu_748_p3 = {{tmp_105_fu_738_p4}, {tmp_104_fu_732_p2}};

assign tmp_111_fu_445_p2 = ((sf_mid2_fu_391_p3 == 9'd255) ? 1'b1 : 1'b0);

assign tmp_255_1_fu_616_p2 = ((tmp_98_fu_608_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_255_2_fu_686_p2 = ((tmp_102_fu_678_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_255_3_fu_756_p2 = ((tmp_110_fu_748_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_256_1_fu_804_p1 = qb_assign_1_1_fu_800_p2;

assign tmp_256_2_fu_827_p1 = qb_assign_1_2_fu_823_p2;

assign tmp_256_3_fu_850_p1 = qb_assign_1_3_fu_846_p2;

assign tmp_68_fu_774_p1 = $signed(tmp_67_reg_1540);

assign tmp_71_fu_797_p1 = $signed(tmp_70_reg_1555);

assign tmp_74_fu_820_p1 = $signed(tmp_73_reg_1570);

assign tmp_77_fu_843_p1 = $signed(tmp_76_reg_1585);

assign tmp_853_fu_385_p2 = (tmp_108_mid_fu_373_p2 | exitcond_flatten_fu_331_p2);

assign tmp_882_fu_367_p2 = ((sf_reg_276 == 9'd256) ? 1'b1 : 1'b0);

assign tmp_924_fu_399_p1 = nm_1_fu_379_p2[5:0];

assign tmp_925_fu_492_p3 = p_Val2_s_fu_486_p2[32'd13];

assign tmp_927_fu_518_p1 = p_Val2_s_fu_486_p2[0:0];

assign tmp_928_fu_562_p3 = p_Val2_1_fu_556_p2[32'd13];

assign tmp_92_fu_522_p2 = (tmp_927_fu_518_p1 | tmp_925_fu_492_p3);

assign tmp_930_fu_588_p1 = p_Val2_1_fu_556_p2[0:0];

assign tmp_931_fu_632_p3 = p_Val2_2_fu_626_p2[32'd13];

assign tmp_933_fu_658_p1 = p_Val2_2_fu_626_p2[0:0];

assign tmp_934_fu_702_p3 = p_Val2_3_fu_696_p2[32'd13];

assign tmp_936_fu_728_p1 = p_Val2_3_fu_696_p2[0:0];

assign tmp_93_fu_528_p4 = {{p_Val2_s_fu_486_p2[5:1]}};

assign tmp_94_fu_538_p3 = {{tmp_93_fu_528_p4}, {tmp_92_fu_522_p2}};

assign tmp_96_fu_592_p2 = (tmp_930_fu_588_p1 | tmp_928_fu_562_p3);

assign tmp_97_fu_598_p4 = {{p_Val2_1_fu_556_p2[5:1]}};

assign tmp_98_fu_608_p3 = {{tmp_97_fu_598_p4}, {tmp_96_fu_592_p2}};

assign tmp_fu_307_p1 = nm_reg_265[5:0];

assign tmp_s_fu_311_p3 = {{tmp_fu_307_p1}, {8'd0}};

assign weights17_m_weights_1_address0 = tmp_107_fu_471_p1;

assign weights17_m_weights_2_address0 = tmp_107_fu_471_p1;

assign weights17_m_weights_3_address0 = tmp_107_fu_471_p1;

assign weights17_m_weights_s_address0 = tmp_107_fu_471_p1;

endmodule //Conv1DMac_new417
