// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv1DMac_new405 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [31:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg in_V_V_read;
reg out_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [13:0] weights13_m_weights_3_address0;
reg    weights13_m_weights_3_ce0;
wire   [6:0] weights13_m_weights_3_q0;
wire   [13:0] weights13_m_weights_2_address0;
reg    weights13_m_weights_2_ce0;
wire   [6:0] weights13_m_weights_2_q0;
wire   [13:0] weights13_m_weights_1_address0;
reg    weights13_m_weights_1_ce0;
wire   [6:0] weights13_m_weights_1_q0;
wire   [13:0] weights13_m_weights_s_address0;
reg    weights13_m_weights_s_ce0;
wire   [6:0] weights13_m_weights_s_q0;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_flatten9_reg_1435;
reg   [0:0] exitcond_flatten9_reg_1435_pp0_iter1_reg;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] tmp_180_reg_1462;
reg   [0:0] tmp_180_reg_1462_pp0_iter3_reg;
reg   [24:0] indvar_flatten9_reg_215;
reg   [15:0] indvar_flatten_reg_226;
reg   [6:0] nm_reg_237;
reg   [8:0] sf_reg_248;
wire   [0:0] exitcond_flatten9_fu_291_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [24:0] indvar_flatten_next9_fu_297_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] nm_t_mid2_fu_391_p3;
reg   [5:0] nm_t_mid2_reg_1444;
reg   [5:0] nm_t_mid2_reg_1444_pp0_iter1_reg;
reg   [5:0] nm_t_mid2_reg_1444_pp0_iter2_reg;
wire   [6:0] nm_mid2_fu_399_p3;
wire   [13:0] tmp_160_fu_411_p2;
reg   [13:0] tmp_160_reg_1457;
wire   [0:0] tmp_180_fu_417_p2;
reg   [0:0] tmp_180_reg_1462_pp0_iter1_reg;
reg   [0:0] tmp_180_reg_1462_pp0_iter2_reg;
wire   [8:0] sf_2_fu_423_p2;
wire   [15:0] indvar_flatten_next_fu_435_p3;
reg   [7:0] tmp_128_reg_1496;
reg   [0:0] tmp_968_reg_1501;
wire   [0:0] tmp_166_fu_518_p2;
reg   [0:0] tmp_166_reg_1506;
reg   [7:0] tmp_130_reg_1511;
reg   [0:0] tmp_971_reg_1516;
wire   [0:0] tmp_279_1_fu_588_p2;
reg   [0:0] tmp_279_1_reg_1521;
reg   [7:0] tmp_132_reg_1526;
reg   [0:0] tmp_974_reg_1531;
wire   [0:0] tmp_279_2_fu_658_p2;
reg   [0:0] tmp_279_2_reg_1536;
reg   [7:0] tmp_134_reg_1541;
reg   [0:0] tmp_977_reg_1546;
wire   [0:0] tmp_279_3_fu_728_p2;
reg   [0:0] tmp_279_3_reg_1551;
wire   [7:0] p_Val2_s_fu_975_p2;
reg   [7:0] p_Val2_s_reg_1556;
wire   [7:0] p_Val2_23_1_fu_1114_p2;
reg   [7:0] p_Val2_23_1_reg_1561;
wire   [7:0] p_Val2_23_2_fu_1253_p2;
reg   [7:0] p_Val2_23_2_reg_1566;
wire   [7:0] p_Val2_23_3_fu_1392_p2;
reg   [7:0] p_Val2_23_3_reg_1571;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
wire   [63:0] tmp_161_fu_443_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] macRegisters_0_V_5_fu_134;
wire   [7:0] macRegisters_0_V_fu_760_p2;
reg   [7:0] macRegisters_1_V_5_fu_138;
wire   [7:0] macRegisters_1_V_fu_779_p2;
reg   [7:0] macRegisters_2_V_5_fu_142;
wire   [7:0] macRegisters_2_V_fu_798_p2;
reg   [7:0] macRegisters_3_V_5_fu_146;
wire   [7:0] macRegisters_3_V_fu_817_p2;
wire   [5:0] tmp_fu_279_p1;
wire   [0:0] exitcond_flatten_fu_303_p2;
wire   [13:0] tmp_s_fu_283_p3;
wire   [0:0] tmp_885_fu_339_p2;
wire   [0:0] not_exitcond_flatten_fu_333_p2;
wire   [6:0] nm_mid_fu_309_p3;
wire   [0:0] tmp_187_mid_fu_345_p2;
wire   [0:0] tmp_859_fu_357_p2;
wire   [6:0] nm_2_fu_351_p2;
wire   [5:0] tmp_966_fu_371_p1;
wire   [13:0] tmp_186_mid1_fu_375_p3;
wire   [13:0] tmp_186_mid_fu_317_p3;
wire   [5:0] nm_t_mid_fu_325_p3;
wire   [8:0] sf_mid2_fu_363_p3;
wire   [13:0] sf_cast1_fu_407_p1;
wire   [13:0] tmp_186_mid2_fu_383_p3;
wire   [15:0] indvar_flatten_op_fu_429_p2;
wire  signed [6:0] p_Val2_s_185_fu_458_p0;
wire  signed [7:0] p_Val2_s_185_fu_458_p1;
wire  signed [14:0] p_08_cast_fu_450_p1;
wire   [14:0] p_Val2_s_185_fu_458_p2;
wire   [0:0] tmp_969_fu_490_p1;
wire   [0:0] tmp_967_fu_464_p3;
wire   [4:0] tmp_164_fu_500_p4;
wire   [0:0] tmp_163_fu_494_p2;
wire   [5:0] tmp_165_fu_510_p3;
wire  signed [6:0] p_Val2_1_fu_528_p0;
wire  signed [7:0] p_Val2_1_fu_528_p1;
wire   [14:0] p_Val2_1_fu_528_p2;
wire   [0:0] tmp_972_fu_560_p1;
wire   [0:0] tmp_970_fu_534_p3;
wire   [4:0] tmp_170_fu_570_p4;
wire   [0:0] tmp_169_fu_564_p2;
wire   [5:0] tmp_171_fu_580_p3;
wire  signed [6:0] p_Val2_2_fu_598_p0;
wire  signed [7:0] p_Val2_2_fu_598_p1;
wire   [14:0] p_Val2_2_fu_598_p2;
wire   [0:0] tmp_975_fu_630_p1;
wire   [0:0] tmp_973_fu_604_p3;
wire   [4:0] tmp_174_fu_640_p4;
wire   [0:0] tmp_173_fu_634_p2;
wire   [5:0] tmp_175_fu_650_p3;
wire  signed [6:0] p_Val2_3_fu_668_p0;
wire  signed [7:0] p_Val2_3_fu_668_p1;
wire   [14:0] p_Val2_3_fu_668_p2;
wire   [0:0] tmp_978_fu_700_p1;
wire   [0:0] tmp_976_fu_674_p3;
wire   [4:0] tmp_178_fu_710_p4;
wire   [0:0] tmp_177_fu_704_p2;
wire   [5:0] tmp_179_fu_720_p3;
wire   [0:0] qb_assign_2_fu_746_p2;
wire   [7:0] tmp_167_fu_750_p1;
wire   [7:0] tmp1_fu_754_p2;
wire   [0:0] qb_assign_2_1_fu_765_p2;
wire   [7:0] tmp_280_1_fu_769_p1;
wire   [7:0] tmp2_fu_773_p2;
wire   [0:0] qb_assign_2_2_fu_784_p2;
wire   [7:0] tmp_280_2_fu_788_p1;
wire   [7:0] tmp3_fu_792_p2;
wire   [0:0] qb_assign_2_3_fu_803_p2;
wire   [7:0] tmp_280_3_fu_807_p1;
wire   [7:0] tmp4_fu_811_p2;
wire   [7:0] tmp_135_fu_842_p66;
wire   [7:0] tmp_136_fu_981_p66;
wire   [7:0] tmp_137_fu_1120_p66;
wire   [7:0] tmp_138_fu_1259_p66;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Conv1DMac_new405_Ffa #(
    .DataWidth( 7 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights13_m_weights_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights13_m_weights_3_address0),
    .ce0(weights13_m_weights_3_ce0),
    .q0(weights13_m_weights_3_q0)
);

Conv1DMac_new405_Gfk #(
    .DataWidth( 7 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights13_m_weights_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights13_m_weights_2_address0),
    .ce0(weights13_m_weights_2_ce0),
    .q0(weights13_m_weights_2_q0)
);

Conv1DMac_new405_Hfu #(
    .DataWidth( 7 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights13_m_weights_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights13_m_weights_1_address0),
    .ce0(weights13_m_weights_1_ce0),
    .q0(weights13_m_weights_1_q0)
);

Conv1DMac_new405_IfE #(
    .DataWidth( 7 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights13_m_weights_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights13_m_weights_s_address0),
    .ce0(weights13_m_weights_s_ce0),
    .q0(weights13_m_weights_s_q0)
);

computeS3_mux_646yd2_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_U67(
    .din0(8'd253),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd0),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(8'd0),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd255),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd255),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd255),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd255),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd255),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd255),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd255),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1444_pp0_iter2_reg),
    .dout(tmp_135_fu_842_p66)
);

computeS3_mux_646yd2_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_U68(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd0),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(8'd0),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd255),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1444_pp0_iter2_reg),
    .dout(tmp_136_fu_981_p66)
);

computeS3_mux_646yd2_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_U69(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd255),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd255),
    .din12(8'd0),
    .din13(8'd0),
    .din14(8'd4),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd255),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd255),
    .din39(8'd255),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd4),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1444_pp0_iter2_reg),
    .dout(tmp_137_fu_1120_p66)
);

computeS3_mux_646yd2_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_U70(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd0),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(8'd255),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd0),
    .din18(8'd1),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd255),
    .din22(8'd0),
    .din23(8'd0),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd2),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd255),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd1),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd255),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1444_pp0_iter2_reg),
    .dout(tmp_138_fu_1259_p66)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten9_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten9_reg_215 <= indvar_flatten_next9_fu_297_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten9_reg_215 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten9_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_226 <= indvar_flatten_next_fu_435_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_226 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_180_reg_1462_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_0_V_5_fu_134 <= macRegisters_0_V_fu_760_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_180_reg_1462_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_0_V_5_fu_134 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_180_reg_1462_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_1_V_5_fu_138 <= macRegisters_1_V_fu_779_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_180_reg_1462_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_1_V_5_fu_138 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_180_reg_1462_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_2_V_5_fu_142 <= macRegisters_2_V_fu_798_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_180_reg_1462_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_2_V_5_fu_142 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_180_reg_1462_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_3_V_5_fu_146 <= macRegisters_3_V_fu_817_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_180_reg_1462_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_3_V_5_fu_146 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten9_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nm_reg_237 <= nm_mid2_fu_399_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nm_reg_237 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten9_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sf_reg_248 <= sf_2_fu_423_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sf_reg_248 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten9_reg_1435 <= exitcond_flatten9_fu_291_p2;
        exitcond_flatten9_reg_1435_pp0_iter1_reg <= exitcond_flatten9_reg_1435;
        nm_t_mid2_reg_1444_pp0_iter1_reg <= nm_t_mid2_reg_1444;
        tmp_180_reg_1462_pp0_iter1_reg <= tmp_180_reg_1462;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten9_fu_291_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nm_t_mid2_reg_1444 <= nm_t_mid2_fu_391_p3;
        tmp_160_reg_1457 <= tmp_160_fu_411_p2;
        tmp_180_reg_1462 <= tmp_180_fu_417_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        nm_t_mid2_reg_1444_pp0_iter2_reg <= nm_t_mid2_reg_1444_pp0_iter1_reg;
        tmp_180_reg_1462_pp0_iter2_reg <= tmp_180_reg_1462_pp0_iter1_reg;
        tmp_180_reg_1462_pp0_iter3_reg <= tmp_180_reg_1462_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_180_reg_1462_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_23_1_reg_1561 <= p_Val2_23_1_fu_1114_p2;
        p_Val2_23_2_reg_1566 <= p_Val2_23_2_fu_1253_p2;
        p_Val2_23_3_reg_1571 <= p_Val2_23_3_fu_1392_p2;
        p_Val2_s_reg_1556 <= p_Val2_s_fu_975_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_128_reg_1496 <= {{p_Val2_s_185_fu_458_p2[14:7]}};
        tmp_130_reg_1511 <= {{p_Val2_1_fu_528_p2[14:7]}};
        tmp_132_reg_1526 <= {{p_Val2_2_fu_598_p2[14:7]}};
        tmp_134_reg_1541 <= {{p_Val2_3_fu_668_p2[14:7]}};
        tmp_166_reg_1506 <= tmp_166_fu_518_p2;
        tmp_279_1_reg_1521 <= tmp_279_1_fu_588_p2;
        tmp_279_2_reg_1536 <= tmp_279_2_fu_658_p2;
        tmp_279_3_reg_1551 <= tmp_279_3_fu_728_p2;
        tmp_968_reg_1501 <= p_Val2_s_185_fu_458_p2[32'd6];
        tmp_971_reg_1516 <= p_Val2_1_fu_528_p2[32'd6];
        tmp_974_reg_1531 <= p_Val2_2_fu_598_p2[32'd6];
        tmp_977_reg_1546 <= p_Val2_3_fu_668_p2[32'd6];
    end
end

always @ (*) begin
    if ((exitcond_flatten9_fu_291_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_180_reg_1462_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_180_reg_1462_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights13_m_weights_1_ce0 = 1'b1;
    end else begin
        weights13_m_weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights13_m_weights_2_ce0 = 1'b1;
    end else begin
        weights13_m_weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights13_m_weights_3_ce0 = 1'b1;
    end else begin
        weights13_m_weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights13_m_weights_s_ce0 = 1'b1;
    end else begin
        weights13_m_weights_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_flatten9_fu_291_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten9_fu_291_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((tmp_180_reg_1462_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_180_reg_1462_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_180_reg_1462_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((exitcond_flatten9_reg_1435_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = ((tmp_180_reg_1462_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign exitcond_flatten9_fu_291_p2 = ((indvar_flatten9_reg_215 == 25'd16777216) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_303_p2 = ((indvar_flatten_reg_226 == 16'd16384) ? 1'b1 : 1'b0);

assign indvar_flatten_next9_fu_297_p2 = (25'd1 + indvar_flatten9_reg_215);

assign indvar_flatten_next_fu_435_p3 = ((exitcond_flatten_fu_303_p2[0:0] === 1'b1) ? 16'd1 : indvar_flatten_op_fu_429_p2);

assign indvar_flatten_op_fu_429_p2 = (indvar_flatten_reg_226 + 16'd1);

assign macRegisters_0_V_fu_760_p2 = (tmp_128_reg_1496 + tmp1_fu_754_p2);

assign macRegisters_1_V_fu_779_p2 = (tmp_130_reg_1511 + tmp2_fu_773_p2);

assign macRegisters_2_V_fu_798_p2 = (tmp_132_reg_1526 + tmp3_fu_792_p2);

assign macRegisters_3_V_fu_817_p2 = (tmp_134_reg_1541 + tmp4_fu_811_p2);

assign nm_2_fu_351_p2 = (7'd1 + nm_mid_fu_309_p3);

assign nm_mid2_fu_399_p3 = ((tmp_187_mid_fu_345_p2[0:0] === 1'b1) ? nm_2_fu_351_p2 : nm_mid_fu_309_p3);

assign nm_mid_fu_309_p3 = ((exitcond_flatten_fu_303_p2[0:0] === 1'b1) ? 7'd0 : nm_reg_237);

assign nm_t_mid2_fu_391_p3 = ((tmp_187_mid_fu_345_p2[0:0] === 1'b1) ? tmp_966_fu_371_p1 : nm_t_mid_fu_325_p3);

assign nm_t_mid_fu_325_p3 = ((exitcond_flatten_fu_303_p2[0:0] === 1'b1) ? 6'd0 : tmp_fu_279_p1);

assign not_exitcond_flatten_fu_333_p2 = (exitcond_flatten_fu_303_p2 ^ 1'd1);

assign out_V_V_din = {{{{p_Val2_23_3_reg_1571}, {p_Val2_23_2_reg_1566}}, {p_Val2_23_1_reg_1561}}, {p_Val2_s_reg_1556}};

assign p_08_cast_fu_450_p1 = $signed(in_V_V_dout);

assign p_Val2_1_fu_528_p0 = weights13_m_weights_2_q0;

assign p_Val2_1_fu_528_p1 = p_08_cast_fu_450_p1;

assign p_Val2_1_fu_528_p2 = ($signed(p_Val2_1_fu_528_p0) * $signed(p_Val2_1_fu_528_p1));

assign p_Val2_23_1_fu_1114_p2 = (macRegisters_1_V_fu_779_p2 + tmp_136_fu_981_p66);

assign p_Val2_23_2_fu_1253_p2 = (macRegisters_2_V_fu_798_p2 + tmp_137_fu_1120_p66);

assign p_Val2_23_3_fu_1392_p2 = (macRegisters_3_V_fu_817_p2 + tmp_138_fu_1259_p66);

assign p_Val2_2_fu_598_p0 = weights13_m_weights_1_q0;

assign p_Val2_2_fu_598_p1 = p_08_cast_fu_450_p1;

assign p_Val2_2_fu_598_p2 = ($signed(p_Val2_2_fu_598_p0) * $signed(p_Val2_2_fu_598_p1));

assign p_Val2_3_fu_668_p0 = weights13_m_weights_s_q0;

assign p_Val2_3_fu_668_p1 = p_08_cast_fu_450_p1;

assign p_Val2_3_fu_668_p2 = ($signed(p_Val2_3_fu_668_p0) * $signed(p_Val2_3_fu_668_p1));

assign p_Val2_s_185_fu_458_p0 = weights13_m_weights_3_q0;

assign p_Val2_s_185_fu_458_p1 = p_08_cast_fu_450_p1;

assign p_Val2_s_185_fu_458_p2 = ($signed(p_Val2_s_185_fu_458_p0) * $signed(p_Val2_s_185_fu_458_p1));

assign p_Val2_s_fu_975_p2 = (macRegisters_0_V_fu_760_p2 + tmp_135_fu_842_p66);

assign qb_assign_2_1_fu_765_p2 = (tmp_971_reg_1516 & tmp_279_1_reg_1521);

assign qb_assign_2_2_fu_784_p2 = (tmp_974_reg_1531 & tmp_279_2_reg_1536);

assign qb_assign_2_3_fu_803_p2 = (tmp_977_reg_1546 & tmp_279_3_reg_1551);

assign qb_assign_2_fu_746_p2 = (tmp_968_reg_1501 & tmp_166_reg_1506);

assign sf_2_fu_423_p2 = (sf_mid2_fu_363_p3 + 9'd1);

assign sf_cast1_fu_407_p1 = sf_mid2_fu_363_p3;

assign sf_mid2_fu_363_p3 = ((tmp_859_fu_357_p2[0:0] === 1'b1) ? 9'd0 : sf_reg_248);

assign start_out = real_start;

assign tmp1_fu_754_p2 = (tmp_167_fu_750_p1 + macRegisters_0_V_5_fu_134);

assign tmp2_fu_773_p2 = (tmp_280_1_fu_769_p1 + macRegisters_1_V_5_fu_138);

assign tmp3_fu_792_p2 = (tmp_280_2_fu_788_p1 + macRegisters_2_V_5_fu_142);

assign tmp4_fu_811_p2 = (tmp_280_3_fu_807_p1 + macRegisters_3_V_5_fu_146);

assign tmp_160_fu_411_p2 = (sf_cast1_fu_407_p1 + tmp_186_mid2_fu_383_p3);

assign tmp_161_fu_443_p1 = tmp_160_reg_1457;

assign tmp_163_fu_494_p2 = (tmp_969_fu_490_p1 | tmp_967_fu_464_p3);

assign tmp_164_fu_500_p4 = {{p_Val2_s_185_fu_458_p2[5:1]}};

assign tmp_165_fu_510_p3 = {{tmp_164_fu_500_p4}, {tmp_163_fu_494_p2}};

assign tmp_166_fu_518_p2 = ((tmp_165_fu_510_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_167_fu_750_p1 = qb_assign_2_fu_746_p2;

assign tmp_169_fu_564_p2 = (tmp_972_fu_560_p1 | tmp_970_fu_534_p3);

assign tmp_170_fu_570_p4 = {{p_Val2_1_fu_528_p2[5:1]}};

assign tmp_171_fu_580_p3 = {{tmp_170_fu_570_p4}, {tmp_169_fu_564_p2}};

assign tmp_173_fu_634_p2 = (tmp_975_fu_630_p1 | tmp_973_fu_604_p3);

assign tmp_174_fu_640_p4 = {{p_Val2_2_fu_598_p2[5:1]}};

assign tmp_175_fu_650_p3 = {{tmp_174_fu_640_p4}, {tmp_173_fu_634_p2}};

assign tmp_177_fu_704_p2 = (tmp_978_fu_700_p1 | tmp_976_fu_674_p3);

assign tmp_178_fu_710_p4 = {{p_Val2_3_fu_668_p2[5:1]}};

assign tmp_179_fu_720_p3 = {{tmp_178_fu_710_p4}, {tmp_177_fu_704_p2}};

assign tmp_180_fu_417_p2 = ((sf_mid2_fu_363_p3 == 9'd255) ? 1'b1 : 1'b0);

assign tmp_186_mid1_fu_375_p3 = {{tmp_966_fu_371_p1}, {8'd0}};

assign tmp_186_mid2_fu_383_p3 = ((tmp_187_mid_fu_345_p2[0:0] === 1'b1) ? tmp_186_mid1_fu_375_p3 : tmp_186_mid_fu_317_p3);

assign tmp_186_mid_fu_317_p3 = ((exitcond_flatten_fu_303_p2[0:0] === 1'b1) ? 14'd0 : tmp_s_fu_283_p3);

assign tmp_187_mid_fu_345_p2 = (tmp_885_fu_339_p2 & not_exitcond_flatten_fu_333_p2);

assign tmp_279_1_fu_588_p2 = ((tmp_171_fu_580_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_279_2_fu_658_p2 = ((tmp_175_fu_650_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_279_3_fu_728_p2 = ((tmp_179_fu_720_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_280_1_fu_769_p1 = qb_assign_2_1_fu_765_p2;

assign tmp_280_2_fu_788_p1 = qb_assign_2_2_fu_784_p2;

assign tmp_280_3_fu_807_p1 = qb_assign_2_3_fu_803_p2;

assign tmp_859_fu_357_p2 = (tmp_187_mid_fu_345_p2 | exitcond_flatten_fu_303_p2);

assign tmp_885_fu_339_p2 = ((sf_reg_248 == 9'd256) ? 1'b1 : 1'b0);

assign tmp_966_fu_371_p1 = nm_2_fu_351_p2[5:0];

assign tmp_967_fu_464_p3 = p_Val2_s_185_fu_458_p2[32'd14];

assign tmp_969_fu_490_p1 = p_Val2_s_185_fu_458_p2[0:0];

assign tmp_970_fu_534_p3 = p_Val2_1_fu_528_p2[32'd14];

assign tmp_972_fu_560_p1 = p_Val2_1_fu_528_p2[0:0];

assign tmp_973_fu_604_p3 = p_Val2_2_fu_598_p2[32'd14];

assign tmp_975_fu_630_p1 = p_Val2_2_fu_598_p2[0:0];

assign tmp_976_fu_674_p3 = p_Val2_3_fu_668_p2[32'd14];

assign tmp_978_fu_700_p1 = p_Val2_3_fu_668_p2[0:0];

assign tmp_fu_279_p1 = nm_reg_237[5:0];

assign tmp_s_fu_283_p3 = {{tmp_fu_279_p1}, {8'd0}};

assign weights13_m_weights_1_address0 = tmp_161_fu_443_p1;

assign weights13_m_weights_2_address0 = tmp_161_fu_443_p1;

assign weights13_m_weights_3_address0 = tmp_161_fu_443_p1;

assign weights13_m_weights_s_address0 = tmp_161_fu_443_p1;

endmodule //Conv1DMac_new405
