-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ResizeStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    in_V_V_empty_n : IN STD_LOGIC;
    in_V_V_read : OUT STD_LOGIC;
    out_V_V_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_V_V_TVALID : OUT STD_LOGIC;
    out_V_V_TREADY : IN STD_LOGIC );
end;


architecture behav of ResizeStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal out_V_V_1_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal out_V_V_1_vld_in : STD_LOGIC;
    signal out_V_V_1_vld_out : STD_LOGIC;
    signal out_V_V_1_ack_in : STD_LOGIC;
    signal out_V_V_1_ack_out : STD_LOGIC;
    signal out_V_V_1_payload_A : STD_LOGIC_VECTOR (63 downto 0);
    signal out_V_V_1_payload_B : STD_LOGIC_VECTOR (63 downto 0);
    signal out_V_V_1_sel_rd : STD_LOGIC := '0';
    signal out_V_V_1_sel_wr : STD_LOGIC := '0';
    signal out_V_V_1_sel : STD_LOGIC;
    signal out_V_V_1_load_A : STD_LOGIC;
    signal out_V_V_1_load_B : STD_LOGIC;
    signal out_V_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_V_V_1_state_cmp_full : STD_LOGIC;
    signal in_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_72_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_1_fu_78_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal i_1_reg_92 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal outWrite_V_fu_84_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_reg_61 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    out_V_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_V_V_1_ack_out = ap_const_logic_1) and (out_V_V_1_vld_out = ap_const_logic_1))) then 
                                        out_V_V_1_sel_rd <= not(out_V_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_V_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_V_V_1_ack_in = ap_const_logic_1) and (out_V_V_1_vld_in = ap_const_logic_1))) then 
                                        out_V_V_1_sel_wr <= not(out_V_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_V_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_V_V_1_state = ap_const_lv2_2) and (out_V_V_1_vld_in = ap_const_logic_0)) or ((out_V_V_1_state = ap_const_lv2_3) and (out_V_V_1_vld_in = ap_const_logic_0) and (out_V_V_1_ack_out = ap_const_logic_1)))) then 
                    out_V_V_1_state <= ap_const_lv2_2;
                elsif ((((out_V_V_1_state = ap_const_lv2_1) and (out_V_V_1_ack_out = ap_const_logic_0)) or ((out_V_V_1_state = ap_const_lv2_3) and (out_V_V_1_ack_out = ap_const_logic_0) and (out_V_V_1_vld_in = ap_const_logic_1)))) then 
                    out_V_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_V_V_1_vld_in = ap_const_logic_0) and (out_V_V_1_ack_out = ap_const_logic_1))) and not(((out_V_V_1_ack_out = ap_const_logic_0) and (out_V_V_1_vld_in = ap_const_logic_1))) and (out_V_V_1_state = ap_const_lv2_3)) or ((out_V_V_1_state = ap_const_lv2_1) and (out_V_V_1_ack_out = ap_const_logic_1)) or ((out_V_V_1_state = ap_const_lv2_2) and (out_V_V_1_vld_in = ap_const_logic_1)))) then 
                    out_V_V_1_state <= ap_const_lv2_3;
                else 
                    out_V_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i_reg_61_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_V_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_reg_61 <= i_1_reg_92;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_61 <= ap_const_lv18_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_1_reg_92 <= i_1_fu_78_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_V_V_1_load_A = ap_const_logic_1)) then
                out_V_V_1_payload_A <= outWrite_V_fu_84_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_V_V_1_load_B = ap_const_logic_1)) then
                out_V_V_1_payload_B <= outWrite_V_fu_84_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, in_V_V_empty_n, out_V_V_1_ack_in, ap_CS_fsm_state2, tmp_fu_72_p2, ap_CS_fsm_state3, ap_block_state2_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((out_V_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(in_V_V_empty_n, out_V_V_1_ack_in, tmp_fu_72_p2)
    begin
                ap_block_state2 <= ((out_V_V_1_ack_in = ap_const_logic_0) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_io_assign_proc : process(out_V_V_1_ack_in, tmp_fu_72_p2)
    begin
                ap_block_state2_io <= ((tmp_fu_72_p2 = ap_const_lv1_0) and (out_V_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, in_V_V_empty_n, out_V_V_1_ack_in, ap_CS_fsm_state2, tmp_fu_72_p2, ap_block_state2_io)
    begin
        if ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(in_V_V_empty_n, out_V_V_1_ack_in, ap_CS_fsm_state2, tmp_fu_72_p2, ap_block_state2_io)
    begin
        if ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_1_fu_78_p2 <= std_logic_vector(unsigned(i_reg_61) + unsigned(ap_const_lv18_1));

    in_V_V_blk_n_assign_proc : process(in_V_V_empty_n, ap_CS_fsm_state2, tmp_fu_72_p2)
    begin
        if (((tmp_fu_72_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_V_V_blk_n <= in_V_V_empty_n;
        else 
            in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_read_assign_proc : process(in_V_V_empty_n, out_V_V_1_ack_in, ap_CS_fsm_state2, tmp_fu_72_p2, ap_block_state2_io)
    begin
        if ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_V_V_read <= ap_const_logic_1;
        else 
            in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    outWrite_V_fu_84_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_V_V_dout),64));
    out_V_V_1_ack_in <= out_V_V_1_state(1);
    out_V_V_1_ack_out <= out_V_V_TREADY;

    out_V_V_1_data_out_assign_proc : process(out_V_V_1_payload_A, out_V_V_1_payload_B, out_V_V_1_sel)
    begin
        if ((out_V_V_1_sel = ap_const_logic_1)) then 
            out_V_V_1_data_out <= out_V_V_1_payload_B;
        else 
            out_V_V_1_data_out <= out_V_V_1_payload_A;
        end if; 
    end process;

    out_V_V_1_load_A <= (out_V_V_1_state_cmp_full and not(out_V_V_1_sel_wr));
    out_V_V_1_load_B <= (out_V_V_1_state_cmp_full and out_V_V_1_sel_wr);
    out_V_V_1_sel <= out_V_V_1_sel_rd;
    out_V_V_1_state_cmp_full <= '0' when (out_V_V_1_state = ap_const_lv2_1) else '1';

    out_V_V_1_vld_in_assign_proc : process(in_V_V_empty_n, out_V_V_1_ack_in, ap_CS_fsm_state2, tmp_fu_72_p2, ap_block_state2_io)
    begin
        if ((not(((out_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_72_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_V_V_1_vld_in <= ap_const_logic_1;
        else 
            out_V_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_V_V_1_vld_out <= out_V_V_1_state(0);
    out_V_V_TDATA <= out_V_V_1_data_out;

    out_V_V_TDATA_blk_n_assign_proc : process(out_V_V_1_state, ap_CS_fsm_state2, tmp_fu_72_p2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((tmp_fu_72_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            out_V_V_TDATA_blk_n <= out_V_V_1_state(1);
        else 
            out_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_V_TVALID <= out_V_V_1_state(0);
    tmp_fu_72_p2 <= "1" when (i_reg_61 = ap_const_lv18_20000) else "0";
end behav;
