// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="computeS4,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z045ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=25689612,HLS_SYN_TPT=16777733,HLS_SYN_MEM=85,HLS_SYN_DSP=0,HLS_SYN_FF=2207,HLS_SYN_LUT=7477,HLS_VERSION=2018_2}" *)

module computeS4 (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        m_axi_hostmem_AWVALID,
        m_axi_hostmem_AWREADY,
        m_axi_hostmem_AWADDR,
        m_axi_hostmem_AWID,
        m_axi_hostmem_AWLEN,
        m_axi_hostmem_AWSIZE,
        m_axi_hostmem_AWBURST,
        m_axi_hostmem_AWLOCK,
        m_axi_hostmem_AWCACHE,
        m_axi_hostmem_AWPROT,
        m_axi_hostmem_AWQOS,
        m_axi_hostmem_AWREGION,
        m_axi_hostmem_AWUSER,
        m_axi_hostmem_WVALID,
        m_axi_hostmem_WREADY,
        m_axi_hostmem_WDATA,
        m_axi_hostmem_WSTRB,
        m_axi_hostmem_WLAST,
        m_axi_hostmem_WID,
        m_axi_hostmem_WUSER,
        m_axi_hostmem_ARVALID,
        m_axi_hostmem_ARREADY,
        m_axi_hostmem_ARADDR,
        m_axi_hostmem_ARID,
        m_axi_hostmem_ARLEN,
        m_axi_hostmem_ARSIZE,
        m_axi_hostmem_ARBURST,
        m_axi_hostmem_ARLOCK,
        m_axi_hostmem_ARCACHE,
        m_axi_hostmem_ARPROT,
        m_axi_hostmem_ARQOS,
        m_axi_hostmem_ARREGION,
        m_axi_hostmem_ARUSER,
        m_axi_hostmem_RVALID,
        m_axi_hostmem_RREADY,
        m_axi_hostmem_RDATA,
        m_axi_hostmem_RLAST,
        m_axi_hostmem_RID,
        m_axi_hostmem_RUSER,
        m_axi_hostmem_RRESP,
        m_axi_hostmem_BVALID,
        m_axi_hostmem_BREADY,
        m_axi_hostmem_BRESP,
        m_axi_hostmem_BID,
        m_axi_hostmem_BUSER,
        input1_V_V_TDATA,
        input1_V_V_TVALID,
        input1_V_V_TREADY,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_ID_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_DATA_WIDTH = 64;
parameter    C_M_AXI_HOSTMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_USER_VALUE = 0;
parameter    C_M_AXI_HOSTMEM_PROT_VALUE = 0;
parameter    C_M_AXI_HOSTMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_HOSTMEM_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   m_axi_hostmem_AWVALID;
input   m_axi_hostmem_AWREADY;
output  [C_M_AXI_HOSTMEM_ADDR_WIDTH - 1:0] m_axi_hostmem_AWADDR;
output  [C_M_AXI_HOSTMEM_ID_WIDTH - 1:0] m_axi_hostmem_AWID;
output  [7:0] m_axi_hostmem_AWLEN;
output  [2:0] m_axi_hostmem_AWSIZE;
output  [1:0] m_axi_hostmem_AWBURST;
output  [1:0] m_axi_hostmem_AWLOCK;
output  [3:0] m_axi_hostmem_AWCACHE;
output  [2:0] m_axi_hostmem_AWPROT;
output  [3:0] m_axi_hostmem_AWQOS;
output  [3:0] m_axi_hostmem_AWREGION;
output  [C_M_AXI_HOSTMEM_AWUSER_WIDTH - 1:0] m_axi_hostmem_AWUSER;
output   m_axi_hostmem_WVALID;
input   m_axi_hostmem_WREADY;
output  [C_M_AXI_HOSTMEM_DATA_WIDTH - 1:0] m_axi_hostmem_WDATA;
output  [C_M_AXI_HOSTMEM_WSTRB_WIDTH - 1:0] m_axi_hostmem_WSTRB;
output   m_axi_hostmem_WLAST;
output  [C_M_AXI_HOSTMEM_ID_WIDTH - 1:0] m_axi_hostmem_WID;
output  [C_M_AXI_HOSTMEM_WUSER_WIDTH - 1:0] m_axi_hostmem_WUSER;
output   m_axi_hostmem_ARVALID;
input   m_axi_hostmem_ARREADY;
output  [C_M_AXI_HOSTMEM_ADDR_WIDTH - 1:0] m_axi_hostmem_ARADDR;
output  [C_M_AXI_HOSTMEM_ID_WIDTH - 1:0] m_axi_hostmem_ARID;
output  [7:0] m_axi_hostmem_ARLEN;
output  [2:0] m_axi_hostmem_ARSIZE;
output  [1:0] m_axi_hostmem_ARBURST;
output  [1:0] m_axi_hostmem_ARLOCK;
output  [3:0] m_axi_hostmem_ARCACHE;
output  [2:0] m_axi_hostmem_ARPROT;
output  [3:0] m_axi_hostmem_ARQOS;
output  [3:0] m_axi_hostmem_ARREGION;
output  [C_M_AXI_HOSTMEM_ARUSER_WIDTH - 1:0] m_axi_hostmem_ARUSER;
input   m_axi_hostmem_RVALID;
output   m_axi_hostmem_RREADY;
input  [C_M_AXI_HOSTMEM_DATA_WIDTH - 1:0] m_axi_hostmem_RDATA;
input   m_axi_hostmem_RLAST;
input  [C_M_AXI_HOSTMEM_ID_WIDTH - 1:0] m_axi_hostmem_RID;
input  [C_M_AXI_HOSTMEM_RUSER_WIDTH - 1:0] m_axi_hostmem_RUSER;
input  [1:0] m_axi_hostmem_RRESP;
input   m_axi_hostmem_BVALID;
output   m_axi_hostmem_BREADY;
input  [1:0] m_axi_hostmem_BRESP;
input  [C_M_AXI_HOSTMEM_ID_WIDTH - 1:0] m_axi_hostmem_BID;
input  [C_M_AXI_HOSTMEM_BUSER_WIDTH - 1:0] m_axi_hostmem_BUSER;
input  [63:0] input1_V_V_TDATA;
input   input1_V_V_TVALID;
output   input1_V_V_TREADY;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire   [31:0] outPtr_V;
wire    hostmem_AWREADY;
wire    hostmem_WREADY;
wire    hostmem_ARREADY;
wire    hostmem_RVALID;
wire   [63:0] hostmem_RDATA;
wire    hostmem_RLAST;
wire   [0:0] hostmem_RID;
wire   [0:0] hostmem_RUSER;
wire   [1:0] hostmem_RRESP;
wire    hostmem_BVALID;
wire   [1:0] hostmem_BRESP;
wire   [0:0] hostmem_BID;
wire   [0:0] hostmem_BUSER;
wire    ResizeStream_14_U0_ap_start;
wire    ResizeStream_14_U0_start_full_n;
wire    ResizeStream_14_U0_ap_done;
wire    ResizeStream_14_U0_ap_continue;
wire    ResizeStream_14_U0_ap_idle;
wire    ResizeStream_14_U0_ap_ready;
wire    ResizeStream_14_U0_start_out;
wire    ResizeStream_14_U0_start_write;
wire    ResizeStream_14_U0_in_V_V_TREADY;
wire   [7:0] ResizeStream_14_U0_out_V_V_din;
wire    ResizeStream_14_U0_out_V_V_write;
wire   [31:0] ResizeStream_14_U0_outPtr_V_out_din;
wire    ResizeStream_14_U0_outPtr_V_out_write;
wire    Conv1DBuffer_new_U0_ap_start;
wire    Conv1DBuffer_new_U0_ap_done;
wire    Conv1DBuffer_new_U0_ap_continue;
wire    Conv1DBuffer_new_U0_ap_idle;
wire    Conv1DBuffer_new_U0_ap_ready;
wire    Conv1DBuffer_new_U0_start_out;
wire    Conv1DBuffer_new_U0_start_write;
wire    Conv1DBuffer_new_U0_in_V_V_read;
wire   [7:0] Conv1DBuffer_new_U0_out_V_V_din;
wire    Conv1DBuffer_new_U0_out_V_V_write;
wire    Conv1DMac_new_U0_ap_start;
wire    Conv1DMac_new_U0_ap_done;
wire    Conv1DMac_new_U0_ap_continue;
wire    Conv1DMac_new_U0_ap_idle;
wire    Conv1DMac_new_U0_ap_ready;
wire    Conv1DMac_new_U0_start_out;
wire    Conv1DMac_new_U0_start_write;
wire    Conv1DMac_new_U0_in_V_V_read;
wire   [31:0] Conv1DMac_new_U0_out_V_V_din;
wire    Conv1DMac_new_U0_out_V_V_write;
wire    Relu1D77_U0_ap_start;
wire    Relu1D77_U0_ap_done;
wire    Relu1D77_U0_ap_continue;
wire    Relu1D77_U0_ap_idle;
wire    Relu1D77_U0_ap_ready;
wire    Relu1D77_U0_start_out;
wire    Relu1D77_U0_start_write;
wire    Relu1D77_U0_in_V_V_read;
wire   [31:0] Relu1D77_U0_out_V_V_din;
wire    Relu1D77_U0_out_V_V_write;
wire    StreamingDataWidthCo_U0_ap_start;
wire    StreamingDataWidthCo_U0_ap_done;
wire    StreamingDataWidthCo_U0_ap_continue;
wire    StreamingDataWidthCo_U0_ap_idle;
wire    StreamingDataWidthCo_U0_ap_ready;
wire    StreamingDataWidthCo_U0_start_out;
wire    StreamingDataWidthCo_U0_start_write;
wire    StreamingDataWidthCo_U0_in_V_V_read;
wire   [7:0] StreamingDataWidthCo_U0_out_V_V_din;
wire    StreamingDataWidthCo_U0_out_V_V_write;
wire    Conv1DBuffer_new_1_U0_ap_start;
wire    Conv1DBuffer_new_1_U0_ap_done;
wire    Conv1DBuffer_new_1_U0_ap_continue;
wire    Conv1DBuffer_new_1_U0_ap_idle;
wire    Conv1DBuffer_new_1_U0_ap_ready;
wire    Conv1DBuffer_new_1_U0_start_out;
wire    Conv1DBuffer_new_1_U0_start_write;
wire    Conv1DBuffer_new_1_U0_in_V_V_read;
wire   [7:0] Conv1DBuffer_new_1_U0_out_V_V_din;
wire    Conv1DBuffer_new_1_U0_out_V_V_write;
wire    Conv1DMac_new_1_U0_ap_start;
wire    Conv1DMac_new_1_U0_ap_done;
wire    Conv1DMac_new_1_U0_ap_continue;
wire    Conv1DMac_new_1_U0_ap_idle;
wire    Conv1DMac_new_1_U0_ap_ready;
wire    Conv1DMac_new_1_U0_start_out;
wire    Conv1DMac_new_1_U0_start_write;
wire    Conv1DMac_new_1_U0_in_V_V_read;
wire   [31:0] Conv1DMac_new_1_U0_out_V_V_din;
wire    Conv1DMac_new_1_U0_out_V_V_write;
wire    Relu1D_U0_ap_start;
wire    Relu1D_U0_ap_done;
wire    Relu1D_U0_ap_continue;
wire    Relu1D_U0_ap_idle;
wire    Relu1D_U0_ap_ready;
wire    Relu1D_U0_start_out;
wire    Relu1D_U0_start_write;
wire    Relu1D_U0_in_V_V_read;
wire   [31:0] Relu1D_U0_out_V_V_din;
wire    Relu1D_U0_out_V_V_write;
wire    StreamingDataWidthCo_1_U0_ap_start;
wire    StreamingDataWidthCo_1_U0_ap_done;
wire    StreamingDataWidthCo_1_U0_ap_continue;
wire    StreamingDataWidthCo_1_U0_ap_idle;
wire    StreamingDataWidthCo_1_U0_ap_ready;
wire    StreamingDataWidthCo_1_U0_start_out;
wire    StreamingDataWidthCo_1_U0_start_write;
wire    StreamingDataWidthCo_1_U0_in_V_V_read;
wire   [7:0] StreamingDataWidthCo_1_U0_out_V_V_din;
wire    StreamingDataWidthCo_1_U0_out_V_V_write;
wire    ResizeStream_U0_ap_start;
wire    ResizeStream_U0_ap_done;
wire    ResizeStream_U0_ap_continue;
wire    ResizeStream_U0_ap_idle;
wire    ResizeStream_U0_ap_ready;
wire    ResizeStream_U0_in_V_V_read;
wire   [63:0] ResizeStream_U0_out_V_V_din;
wire    ResizeStream_U0_out_V_V_write;
wire    Stream2Mem_U0_ap_start;
wire    Stream2Mem_U0_ap_done;
wire    Stream2Mem_U0_ap_continue;
wire    Stream2Mem_U0_ap_idle;
wire    Stream2Mem_U0_ap_ready;
wire    Stream2Mem_U0_in_V_V_read;
wire    Stream2Mem_U0_m_axi_out_V_AWVALID;
wire   [31:0] Stream2Mem_U0_m_axi_out_V_AWADDR;
wire   [0:0] Stream2Mem_U0_m_axi_out_V_AWID;
wire   [31:0] Stream2Mem_U0_m_axi_out_V_AWLEN;
wire   [2:0] Stream2Mem_U0_m_axi_out_V_AWSIZE;
wire   [1:0] Stream2Mem_U0_m_axi_out_V_AWBURST;
wire   [1:0] Stream2Mem_U0_m_axi_out_V_AWLOCK;
wire   [3:0] Stream2Mem_U0_m_axi_out_V_AWCACHE;
wire   [2:0] Stream2Mem_U0_m_axi_out_V_AWPROT;
wire   [3:0] Stream2Mem_U0_m_axi_out_V_AWQOS;
wire   [3:0] Stream2Mem_U0_m_axi_out_V_AWREGION;
wire   [0:0] Stream2Mem_U0_m_axi_out_V_AWUSER;
wire    Stream2Mem_U0_m_axi_out_V_WVALID;
wire   [63:0] Stream2Mem_U0_m_axi_out_V_WDATA;
wire   [7:0] Stream2Mem_U0_m_axi_out_V_WSTRB;
wire    Stream2Mem_U0_m_axi_out_V_WLAST;
wire   [0:0] Stream2Mem_U0_m_axi_out_V_WID;
wire   [0:0] Stream2Mem_U0_m_axi_out_V_WUSER;
wire    Stream2Mem_U0_m_axi_out_V_ARVALID;
wire   [31:0] Stream2Mem_U0_m_axi_out_V_ARADDR;
wire   [0:0] Stream2Mem_U0_m_axi_out_V_ARID;
wire   [31:0] Stream2Mem_U0_m_axi_out_V_ARLEN;
wire   [2:0] Stream2Mem_U0_m_axi_out_V_ARSIZE;
wire   [1:0] Stream2Mem_U0_m_axi_out_V_ARBURST;
wire   [1:0] Stream2Mem_U0_m_axi_out_V_ARLOCK;
wire   [3:0] Stream2Mem_U0_m_axi_out_V_ARCACHE;
wire   [2:0] Stream2Mem_U0_m_axi_out_V_ARPROT;
wire   [3:0] Stream2Mem_U0_m_axi_out_V_ARQOS;
wire   [3:0] Stream2Mem_U0_m_axi_out_V_ARREGION;
wire   [0:0] Stream2Mem_U0_m_axi_out_V_ARUSER;
wire    Stream2Mem_U0_m_axi_out_V_RREADY;
wire    Stream2Mem_U0_m_axi_out_V_BREADY;
wire    Stream2Mem_U0_out_V_offset_read;
wire    ap_sync_continue;
wire    cnv_87_V_V_full_n;
wire   [7:0] cnv_87_V_V_dout;
wire    cnv_87_V_V_empty_n;
wire    outPtr_V_c_full_n;
wire   [31:0] outPtr_V_c_dout;
wire    outPtr_V_c_empty_n;
wire    cnv_88_V_V_full_n;
wire   [7:0] cnv_88_V_V_dout;
wire    cnv_88_V_V_empty_n;
wire    cnv_89PRL_V_V_full_n;
wire   [31:0] cnv_89PRL_V_V_dout;
wire    cnv_89PRL_V_V_empty_n;
wire    cnv_90PRL_V_V_full_n;
wire   [31:0] cnv_90PRL_V_V_dout;
wire    cnv_90PRL_V_V_empty_n;
wire    cnv_91_V_V_full_n;
wire   [7:0] cnv_91_V_V_dout;
wire    cnv_91_V_V_empty_n;
wire    cnv_92_V_V_full_n;
wire   [7:0] cnv_92_V_V_dout;
wire    cnv_92_V_V_empty_n;
wire    cnv_93PRL_V_V_full_n;
wire   [31:0] cnv_93PRL_V_V_dout;
wire    cnv_93PRL_V_V_empty_n;
wire    cnv_94PRL_V_V_full_n;
wire   [31:0] cnv_94PRL_V_V_dout;
wire    cnv_94PRL_V_V_empty_n;
wire    outStr_V_V_full_n;
wire   [7:0] outStr_V_V_dout;
wire    outStr_V_V_empty_n;
wire    s4_out_V_V_full_n;
wire   [63:0] s4_out_V_V_dout;
wire    s4_out_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Conv1DBuffer_new_U0_din;
wire    start_for_Conv1DBuffer_new_U0_full_n;
wire   [0:0] start_for_Conv1DBuffer_new_U0_dout;
wire    start_for_Conv1DBuffer_new_U0_empty_n;
wire   [0:0] start_for_Stream2Mem_U0_din;
wire    start_for_Stream2Mem_U0_full_n;
wire   [0:0] start_for_Stream2Mem_U0_dout;
wire    start_for_Stream2Mem_U0_empty_n;
wire   [0:0] start_for_Conv1DMac_new_U0_din;
wire    start_for_Conv1DMac_new_U0_full_n;
wire   [0:0] start_for_Conv1DMac_new_U0_dout;
wire    start_for_Conv1DMac_new_U0_empty_n;
wire   [0:0] start_for_Relu1D77_U0_din;
wire    start_for_Relu1D77_U0_full_n;
wire   [0:0] start_for_Relu1D77_U0_dout;
wire    start_for_Relu1D77_U0_empty_n;
wire   [0:0] start_for_StreamingDataWidthCo_U0_din;
wire    start_for_StreamingDataWidthCo_U0_full_n;
wire   [0:0] start_for_StreamingDataWidthCo_U0_dout;
wire    start_for_StreamingDataWidthCo_U0_empty_n;
wire   [0:0] start_for_Conv1DBuffer_new_1_U0_din;
wire    start_for_Conv1DBuffer_new_1_U0_full_n;
wire   [0:0] start_for_Conv1DBuffer_new_1_U0_dout;
wire    start_for_Conv1DBuffer_new_1_U0_empty_n;
wire   [0:0] start_for_Conv1DMac_new_1_U0_din;
wire    start_for_Conv1DMac_new_1_U0_full_n;
wire   [0:0] start_for_Conv1DMac_new_1_U0_dout;
wire    start_for_Conv1DMac_new_1_U0_empty_n;
wire   [0:0] start_for_Relu1D_U0_din;
wire    start_for_Relu1D_U0_full_n;
wire   [0:0] start_for_Relu1D_U0_dout;
wire    start_for_Relu1D_U0_empty_n;
wire   [0:0] start_for_StreamingDataWidthCo_1_U0_din;
wire    start_for_StreamingDataWidthCo_1_U0_full_n;
wire   [0:0] start_for_StreamingDataWidthCo_1_U0_dout;
wire    start_for_StreamingDataWidthCo_1_U0_empty_n;
wire   [0:0] start_for_ResizeStream_U0_din;
wire    start_for_ResizeStream_U0_full_n;
wire   [0:0] start_for_ResizeStream_U0_dout;
wire    start_for_ResizeStream_U0_empty_n;
wire    ResizeStream_U0_start_full_n;
wire    ResizeStream_U0_start_write;
wire    Stream2Mem_U0_start_full_n;
wire    Stream2Mem_U0_start_write;

computeS4_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
computeS4_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .outPtr_V(outPtr_V)
);

computeS4_hostmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_HOSTMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_HOSTMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_HOSTMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_HOSTMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_HOSTMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_HOSTMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_HOSTMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_HOSTMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_HOSTMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_HOSTMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_HOSTMEM_CACHE_VALUE ))
computeS4_hostmem_m_axi_U(
    .AWVALID(m_axi_hostmem_AWVALID),
    .AWREADY(m_axi_hostmem_AWREADY),
    .AWADDR(m_axi_hostmem_AWADDR),
    .AWID(m_axi_hostmem_AWID),
    .AWLEN(m_axi_hostmem_AWLEN),
    .AWSIZE(m_axi_hostmem_AWSIZE),
    .AWBURST(m_axi_hostmem_AWBURST),
    .AWLOCK(m_axi_hostmem_AWLOCK),
    .AWCACHE(m_axi_hostmem_AWCACHE),
    .AWPROT(m_axi_hostmem_AWPROT),
    .AWQOS(m_axi_hostmem_AWQOS),
    .AWREGION(m_axi_hostmem_AWREGION),
    .AWUSER(m_axi_hostmem_AWUSER),
    .WVALID(m_axi_hostmem_WVALID),
    .WREADY(m_axi_hostmem_WREADY),
    .WDATA(m_axi_hostmem_WDATA),
    .WSTRB(m_axi_hostmem_WSTRB),
    .WLAST(m_axi_hostmem_WLAST),
    .WID(m_axi_hostmem_WID),
    .WUSER(m_axi_hostmem_WUSER),
    .ARVALID(m_axi_hostmem_ARVALID),
    .ARREADY(m_axi_hostmem_ARREADY),
    .ARADDR(m_axi_hostmem_ARADDR),
    .ARID(m_axi_hostmem_ARID),
    .ARLEN(m_axi_hostmem_ARLEN),
    .ARSIZE(m_axi_hostmem_ARSIZE),
    .ARBURST(m_axi_hostmem_ARBURST),
    .ARLOCK(m_axi_hostmem_ARLOCK),
    .ARCACHE(m_axi_hostmem_ARCACHE),
    .ARPROT(m_axi_hostmem_ARPROT),
    .ARQOS(m_axi_hostmem_ARQOS),
    .ARREGION(m_axi_hostmem_ARREGION),
    .ARUSER(m_axi_hostmem_ARUSER),
    .RVALID(m_axi_hostmem_RVALID),
    .RREADY(m_axi_hostmem_RREADY),
    .RDATA(m_axi_hostmem_RDATA),
    .RLAST(m_axi_hostmem_RLAST),
    .RID(m_axi_hostmem_RID),
    .RUSER(m_axi_hostmem_RUSER),
    .RRESP(m_axi_hostmem_RRESP),
    .BVALID(m_axi_hostmem_BVALID),
    .BREADY(m_axi_hostmem_BREADY),
    .BRESP(m_axi_hostmem_BRESP),
    .BID(m_axi_hostmem_BID),
    .BUSER(m_axi_hostmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(hostmem_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(hostmem_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(hostmem_RDATA),
    .I_RID(hostmem_RID),
    .I_RUSER(hostmem_RUSER),
    .I_RRESP(hostmem_RRESP),
    .I_RLAST(hostmem_RLAST),
    .I_AWVALID(Stream2Mem_U0_m_axi_out_V_AWVALID),
    .I_AWREADY(hostmem_AWREADY),
    .I_AWADDR(Stream2Mem_U0_m_axi_out_V_AWADDR),
    .I_AWID(Stream2Mem_U0_m_axi_out_V_AWID),
    .I_AWLEN(Stream2Mem_U0_m_axi_out_V_AWLEN),
    .I_AWSIZE(Stream2Mem_U0_m_axi_out_V_AWSIZE),
    .I_AWLOCK(Stream2Mem_U0_m_axi_out_V_AWLOCK),
    .I_AWCACHE(Stream2Mem_U0_m_axi_out_V_AWCACHE),
    .I_AWQOS(Stream2Mem_U0_m_axi_out_V_AWQOS),
    .I_AWPROT(Stream2Mem_U0_m_axi_out_V_AWPROT),
    .I_AWUSER(Stream2Mem_U0_m_axi_out_V_AWUSER),
    .I_AWBURST(Stream2Mem_U0_m_axi_out_V_AWBURST),
    .I_AWREGION(Stream2Mem_U0_m_axi_out_V_AWREGION),
    .I_WVALID(Stream2Mem_U0_m_axi_out_V_WVALID),
    .I_WREADY(hostmem_WREADY),
    .I_WDATA(Stream2Mem_U0_m_axi_out_V_WDATA),
    .I_WID(Stream2Mem_U0_m_axi_out_V_WID),
    .I_WUSER(Stream2Mem_U0_m_axi_out_V_WUSER),
    .I_WLAST(Stream2Mem_U0_m_axi_out_V_WLAST),
    .I_WSTRB(Stream2Mem_U0_m_axi_out_V_WSTRB),
    .I_BVALID(hostmem_BVALID),
    .I_BREADY(Stream2Mem_U0_m_axi_out_V_BREADY),
    .I_BRESP(hostmem_BRESP),
    .I_BID(hostmem_BID),
    .I_BUSER(hostmem_BUSER)
);

ResizeStream_14 ResizeStream_14_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ResizeStream_14_U0_ap_start),
    .start_full_n(ResizeStream_14_U0_start_full_n),
    .ap_done(ResizeStream_14_U0_ap_done),
    .ap_continue(ResizeStream_14_U0_ap_continue),
    .ap_idle(ResizeStream_14_U0_ap_idle),
    .ap_ready(ResizeStream_14_U0_ap_ready),
    .start_out(ResizeStream_14_U0_start_out),
    .start_write(ResizeStream_14_U0_start_write),
    .in_V_V_TDATA(input1_V_V_TDATA),
    .in_V_V_TVALID(input1_V_V_TVALID),
    .in_V_V_TREADY(ResizeStream_14_U0_in_V_V_TREADY),
    .out_V_V_din(ResizeStream_14_U0_out_V_V_din),
    .out_V_V_full_n(cnv_87_V_V_full_n),
    .out_V_V_write(ResizeStream_14_U0_out_V_V_write),
    .outPtr_V(outPtr_V),
    .outPtr_V_out_din(ResizeStream_14_U0_outPtr_V_out_din),
    .outPtr_V_out_full_n(outPtr_V_c_full_n),
    .outPtr_V_out_write(ResizeStream_14_U0_outPtr_V_out_write)
);

Conv1DBuffer_new Conv1DBuffer_new_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Conv1DBuffer_new_U0_ap_start),
    .start_full_n(start_for_Conv1DMac_new_U0_full_n),
    .ap_done(Conv1DBuffer_new_U0_ap_done),
    .ap_continue(Conv1DBuffer_new_U0_ap_continue),
    .ap_idle(Conv1DBuffer_new_U0_ap_idle),
    .ap_ready(Conv1DBuffer_new_U0_ap_ready),
    .start_out(Conv1DBuffer_new_U0_start_out),
    .start_write(Conv1DBuffer_new_U0_start_write),
    .in_V_V_dout(cnv_87_V_V_dout),
    .in_V_V_empty_n(cnv_87_V_V_empty_n),
    .in_V_V_read(Conv1DBuffer_new_U0_in_V_V_read),
    .out_V_V_din(Conv1DBuffer_new_U0_out_V_V_din),
    .out_V_V_full_n(cnv_88_V_V_full_n),
    .out_V_V_write(Conv1DBuffer_new_U0_out_V_V_write)
);

Conv1DMac_new Conv1DMac_new_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Conv1DMac_new_U0_ap_start),
    .start_full_n(start_for_Relu1D77_U0_full_n),
    .ap_done(Conv1DMac_new_U0_ap_done),
    .ap_continue(Conv1DMac_new_U0_ap_continue),
    .ap_idle(Conv1DMac_new_U0_ap_idle),
    .ap_ready(Conv1DMac_new_U0_ap_ready),
    .start_out(Conv1DMac_new_U0_start_out),
    .start_write(Conv1DMac_new_U0_start_write),
    .in_V_V_dout(cnv_88_V_V_dout),
    .in_V_V_empty_n(cnv_88_V_V_empty_n),
    .in_V_V_read(Conv1DMac_new_U0_in_V_V_read),
    .out_V_V_din(Conv1DMac_new_U0_out_V_V_din),
    .out_V_V_full_n(cnv_89PRL_V_V_full_n),
    .out_V_V_write(Conv1DMac_new_U0_out_V_V_write)
);

Relu1D77 Relu1D77_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Relu1D77_U0_ap_start),
    .start_full_n(start_for_StreamingDataWidthCo_U0_full_n),
    .ap_done(Relu1D77_U0_ap_done),
    .ap_continue(Relu1D77_U0_ap_continue),
    .ap_idle(Relu1D77_U0_ap_idle),
    .ap_ready(Relu1D77_U0_ap_ready),
    .start_out(Relu1D77_U0_start_out),
    .start_write(Relu1D77_U0_start_write),
    .in_V_V_dout(cnv_89PRL_V_V_dout),
    .in_V_V_empty_n(cnv_89PRL_V_V_empty_n),
    .in_V_V_read(Relu1D77_U0_in_V_V_read),
    .out_V_V_din(Relu1D77_U0_out_V_V_din),
    .out_V_V_full_n(cnv_90PRL_V_V_full_n),
    .out_V_V_write(Relu1D77_U0_out_V_V_write)
);

StreamingDataWidthCo StreamingDataWidthCo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(StreamingDataWidthCo_U0_ap_start),
    .start_full_n(start_for_Conv1DBuffer_new_1_U0_full_n),
    .ap_done(StreamingDataWidthCo_U0_ap_done),
    .ap_continue(StreamingDataWidthCo_U0_ap_continue),
    .ap_idle(StreamingDataWidthCo_U0_ap_idle),
    .ap_ready(StreamingDataWidthCo_U0_ap_ready),
    .start_out(StreamingDataWidthCo_U0_start_out),
    .start_write(StreamingDataWidthCo_U0_start_write),
    .in_V_V_dout(cnv_90PRL_V_V_dout),
    .in_V_V_empty_n(cnv_90PRL_V_V_empty_n),
    .in_V_V_read(StreamingDataWidthCo_U0_in_V_V_read),
    .out_V_V_din(StreamingDataWidthCo_U0_out_V_V_din),
    .out_V_V_full_n(cnv_91_V_V_full_n),
    .out_V_V_write(StreamingDataWidthCo_U0_out_V_V_write)
);

Conv1DBuffer_new_1 Conv1DBuffer_new_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Conv1DBuffer_new_1_U0_ap_start),
    .start_full_n(start_for_Conv1DMac_new_1_U0_full_n),
    .ap_done(Conv1DBuffer_new_1_U0_ap_done),
    .ap_continue(Conv1DBuffer_new_1_U0_ap_continue),
    .ap_idle(Conv1DBuffer_new_1_U0_ap_idle),
    .ap_ready(Conv1DBuffer_new_1_U0_ap_ready),
    .start_out(Conv1DBuffer_new_1_U0_start_out),
    .start_write(Conv1DBuffer_new_1_U0_start_write),
    .in_V_V_dout(cnv_91_V_V_dout),
    .in_V_V_empty_n(cnv_91_V_V_empty_n),
    .in_V_V_read(Conv1DBuffer_new_1_U0_in_V_V_read),
    .out_V_V_din(Conv1DBuffer_new_1_U0_out_V_V_din),
    .out_V_V_full_n(cnv_92_V_V_full_n),
    .out_V_V_write(Conv1DBuffer_new_1_U0_out_V_V_write)
);

Conv1DMac_new_1 Conv1DMac_new_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Conv1DMac_new_1_U0_ap_start),
    .start_full_n(start_for_Relu1D_U0_full_n),
    .ap_done(Conv1DMac_new_1_U0_ap_done),
    .ap_continue(Conv1DMac_new_1_U0_ap_continue),
    .ap_idle(Conv1DMac_new_1_U0_ap_idle),
    .ap_ready(Conv1DMac_new_1_U0_ap_ready),
    .start_out(Conv1DMac_new_1_U0_start_out),
    .start_write(Conv1DMac_new_1_U0_start_write),
    .in_V_V_dout(cnv_92_V_V_dout),
    .in_V_V_empty_n(cnv_92_V_V_empty_n),
    .in_V_V_read(Conv1DMac_new_1_U0_in_V_V_read),
    .out_V_V_din(Conv1DMac_new_1_U0_out_V_V_din),
    .out_V_V_full_n(cnv_93PRL_V_V_full_n),
    .out_V_V_write(Conv1DMac_new_1_U0_out_V_V_write)
);

Relu1D Relu1D_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Relu1D_U0_ap_start),
    .start_full_n(start_for_StreamingDataWidthCo_1_U0_full_n),
    .ap_done(Relu1D_U0_ap_done),
    .ap_continue(Relu1D_U0_ap_continue),
    .ap_idle(Relu1D_U0_ap_idle),
    .ap_ready(Relu1D_U0_ap_ready),
    .start_out(Relu1D_U0_start_out),
    .start_write(Relu1D_U0_start_write),
    .in_V_V_dout(cnv_93PRL_V_V_dout),
    .in_V_V_empty_n(cnv_93PRL_V_V_empty_n),
    .in_V_V_read(Relu1D_U0_in_V_V_read),
    .out_V_V_din(Relu1D_U0_out_V_V_din),
    .out_V_V_full_n(cnv_94PRL_V_V_full_n),
    .out_V_V_write(Relu1D_U0_out_V_V_write)
);

StreamingDataWidthCo_1 StreamingDataWidthCo_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(StreamingDataWidthCo_1_U0_ap_start),
    .start_full_n(start_for_ResizeStream_U0_full_n),
    .ap_done(StreamingDataWidthCo_1_U0_ap_done),
    .ap_continue(StreamingDataWidthCo_1_U0_ap_continue),
    .ap_idle(StreamingDataWidthCo_1_U0_ap_idle),
    .ap_ready(StreamingDataWidthCo_1_U0_ap_ready),
    .start_out(StreamingDataWidthCo_1_U0_start_out),
    .start_write(StreamingDataWidthCo_1_U0_start_write),
    .in_V_V_dout(cnv_94PRL_V_V_dout),
    .in_V_V_empty_n(cnv_94PRL_V_V_empty_n),
    .in_V_V_read(StreamingDataWidthCo_1_U0_in_V_V_read),
    .out_V_V_din(StreamingDataWidthCo_1_U0_out_V_V_din),
    .out_V_V_full_n(outStr_V_V_full_n),
    .out_V_V_write(StreamingDataWidthCo_1_U0_out_V_V_write)
);

ResizeStream ResizeStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ResizeStream_U0_ap_start),
    .ap_done(ResizeStream_U0_ap_done),
    .ap_continue(ResizeStream_U0_ap_continue),
    .ap_idle(ResizeStream_U0_ap_idle),
    .ap_ready(ResizeStream_U0_ap_ready),
    .in_V_V_dout(outStr_V_V_dout),
    .in_V_V_empty_n(outStr_V_V_empty_n),
    .in_V_V_read(ResizeStream_U0_in_V_V_read),
    .out_V_V_din(ResizeStream_U0_out_V_V_din),
    .out_V_V_full_n(s4_out_V_V_full_n),
    .out_V_V_write(ResizeStream_U0_out_V_V_write)
);

Stream2Mem Stream2Mem_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Stream2Mem_U0_ap_start),
    .ap_done(Stream2Mem_U0_ap_done),
    .ap_continue(Stream2Mem_U0_ap_continue),
    .ap_idle(Stream2Mem_U0_ap_idle),
    .ap_ready(Stream2Mem_U0_ap_ready),
    .in_V_V_dout(s4_out_V_V_dout),
    .in_V_V_empty_n(s4_out_V_V_empty_n),
    .in_V_V_read(Stream2Mem_U0_in_V_V_read),
    .m_axi_out_V_AWVALID(Stream2Mem_U0_m_axi_out_V_AWVALID),
    .m_axi_out_V_AWREADY(hostmem_AWREADY),
    .m_axi_out_V_AWADDR(Stream2Mem_U0_m_axi_out_V_AWADDR),
    .m_axi_out_V_AWID(Stream2Mem_U0_m_axi_out_V_AWID),
    .m_axi_out_V_AWLEN(Stream2Mem_U0_m_axi_out_V_AWLEN),
    .m_axi_out_V_AWSIZE(Stream2Mem_U0_m_axi_out_V_AWSIZE),
    .m_axi_out_V_AWBURST(Stream2Mem_U0_m_axi_out_V_AWBURST),
    .m_axi_out_V_AWLOCK(Stream2Mem_U0_m_axi_out_V_AWLOCK),
    .m_axi_out_V_AWCACHE(Stream2Mem_U0_m_axi_out_V_AWCACHE),
    .m_axi_out_V_AWPROT(Stream2Mem_U0_m_axi_out_V_AWPROT),
    .m_axi_out_V_AWQOS(Stream2Mem_U0_m_axi_out_V_AWQOS),
    .m_axi_out_V_AWREGION(Stream2Mem_U0_m_axi_out_V_AWREGION),
    .m_axi_out_V_AWUSER(Stream2Mem_U0_m_axi_out_V_AWUSER),
    .m_axi_out_V_WVALID(Stream2Mem_U0_m_axi_out_V_WVALID),
    .m_axi_out_V_WREADY(hostmem_WREADY),
    .m_axi_out_V_WDATA(Stream2Mem_U0_m_axi_out_V_WDATA),
    .m_axi_out_V_WSTRB(Stream2Mem_U0_m_axi_out_V_WSTRB),
    .m_axi_out_V_WLAST(Stream2Mem_U0_m_axi_out_V_WLAST),
    .m_axi_out_V_WID(Stream2Mem_U0_m_axi_out_V_WID),
    .m_axi_out_V_WUSER(Stream2Mem_U0_m_axi_out_V_WUSER),
    .m_axi_out_V_ARVALID(Stream2Mem_U0_m_axi_out_V_ARVALID),
    .m_axi_out_V_ARREADY(1'b0),
    .m_axi_out_V_ARADDR(Stream2Mem_U0_m_axi_out_V_ARADDR),
    .m_axi_out_V_ARID(Stream2Mem_U0_m_axi_out_V_ARID),
    .m_axi_out_V_ARLEN(Stream2Mem_U0_m_axi_out_V_ARLEN),
    .m_axi_out_V_ARSIZE(Stream2Mem_U0_m_axi_out_V_ARSIZE),
    .m_axi_out_V_ARBURST(Stream2Mem_U0_m_axi_out_V_ARBURST),
    .m_axi_out_V_ARLOCK(Stream2Mem_U0_m_axi_out_V_ARLOCK),
    .m_axi_out_V_ARCACHE(Stream2Mem_U0_m_axi_out_V_ARCACHE),
    .m_axi_out_V_ARPROT(Stream2Mem_U0_m_axi_out_V_ARPROT),
    .m_axi_out_V_ARQOS(Stream2Mem_U0_m_axi_out_V_ARQOS),
    .m_axi_out_V_ARREGION(Stream2Mem_U0_m_axi_out_V_ARREGION),
    .m_axi_out_V_ARUSER(Stream2Mem_U0_m_axi_out_V_ARUSER),
    .m_axi_out_V_RVALID(1'b0),
    .m_axi_out_V_RREADY(Stream2Mem_U0_m_axi_out_V_RREADY),
    .m_axi_out_V_RDATA(64'd0),
    .m_axi_out_V_RLAST(1'b0),
    .m_axi_out_V_RID(1'd0),
    .m_axi_out_V_RUSER(1'd0),
    .m_axi_out_V_RRESP(2'd0),
    .m_axi_out_V_BVALID(hostmem_BVALID),
    .m_axi_out_V_BREADY(Stream2Mem_U0_m_axi_out_V_BREADY),
    .m_axi_out_V_BRESP(hostmem_BRESP),
    .m_axi_out_V_BID(hostmem_BID),
    .m_axi_out_V_BUSER(hostmem_BUSER),
    .out_V_offset_dout(outPtr_V_c_dout),
    .out_V_offset_empty_n(outPtr_V_c_empty_n),
    .out_V_offset_read(Stream2Mem_U0_out_V_offset_read)
);

fifo_w8_d2_A cnv_87_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ResizeStream_14_U0_out_V_V_din),
    .if_full_n(cnv_87_V_V_full_n),
    .if_write(ResizeStream_14_U0_out_V_V_write),
    .if_dout(cnv_87_V_V_dout),
    .if_empty_n(cnv_87_V_V_empty_n),
    .if_read(Conv1DBuffer_new_U0_in_V_V_read)
);

fifo_w32_d11_A outPtr_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ResizeStream_14_U0_outPtr_V_out_din),
    .if_full_n(outPtr_V_c_full_n),
    .if_write(ResizeStream_14_U0_outPtr_V_out_write),
    .if_dout(outPtr_V_c_dout),
    .if_empty_n(outPtr_V_c_empty_n),
    .if_read(Stream2Mem_U0_out_V_offset_read)
);

fifo_w8_d2_A cnv_88_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Conv1DBuffer_new_U0_out_V_V_din),
    .if_full_n(cnv_88_V_V_full_n),
    .if_write(Conv1DBuffer_new_U0_out_V_V_write),
    .if_dout(cnv_88_V_V_dout),
    .if_empty_n(cnv_88_V_V_empty_n),
    .if_read(Conv1DMac_new_U0_in_V_V_read)
);

fifo_w32_d2_A cnv_89PRL_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Conv1DMac_new_U0_out_V_V_din),
    .if_full_n(cnv_89PRL_V_V_full_n),
    .if_write(Conv1DMac_new_U0_out_V_V_write),
    .if_dout(cnv_89PRL_V_V_dout),
    .if_empty_n(cnv_89PRL_V_V_empty_n),
    .if_read(Relu1D77_U0_in_V_V_read)
);

fifo_w32_d2_A cnv_90PRL_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Relu1D77_U0_out_V_V_din),
    .if_full_n(cnv_90PRL_V_V_full_n),
    .if_write(Relu1D77_U0_out_V_V_write),
    .if_dout(cnv_90PRL_V_V_dout),
    .if_empty_n(cnv_90PRL_V_V_empty_n),
    .if_read(StreamingDataWidthCo_U0_in_V_V_read)
);

fifo_w8_d2_A cnv_91_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(StreamingDataWidthCo_U0_out_V_V_din),
    .if_full_n(cnv_91_V_V_full_n),
    .if_write(StreamingDataWidthCo_U0_out_V_V_write),
    .if_dout(cnv_91_V_V_dout),
    .if_empty_n(cnv_91_V_V_empty_n),
    .if_read(Conv1DBuffer_new_1_U0_in_V_V_read)
);

fifo_w8_d2_A cnv_92_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Conv1DBuffer_new_1_U0_out_V_V_din),
    .if_full_n(cnv_92_V_V_full_n),
    .if_write(Conv1DBuffer_new_1_U0_out_V_V_write),
    .if_dout(cnv_92_V_V_dout),
    .if_empty_n(cnv_92_V_V_empty_n),
    .if_read(Conv1DMac_new_1_U0_in_V_V_read)
);

fifo_w32_d2_A cnv_93PRL_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Conv1DMac_new_1_U0_out_V_V_din),
    .if_full_n(cnv_93PRL_V_V_full_n),
    .if_write(Conv1DMac_new_1_U0_out_V_V_write),
    .if_dout(cnv_93PRL_V_V_dout),
    .if_empty_n(cnv_93PRL_V_V_empty_n),
    .if_read(Relu1D_U0_in_V_V_read)
);

fifo_w32_d2_A cnv_94PRL_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Relu1D_U0_out_V_V_din),
    .if_full_n(cnv_94PRL_V_V_full_n),
    .if_write(Relu1D_U0_out_V_V_write),
    .if_dout(cnv_94PRL_V_V_dout),
    .if_empty_n(cnv_94PRL_V_V_empty_n),
    .if_read(StreamingDataWidthCo_1_U0_in_V_V_read)
);

fifo_w8_d2_A outStr_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(StreamingDataWidthCo_1_U0_out_V_V_din),
    .if_full_n(outStr_V_V_full_n),
    .if_write(StreamingDataWidthCo_1_U0_out_V_V_write),
    .if_dout(outStr_V_V_dout),
    .if_empty_n(outStr_V_V_empty_n),
    .if_read(ResizeStream_U0_in_V_V_read)
);

fifo_w64_d2_A s4_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ResizeStream_U0_out_V_V_din),
    .if_full_n(s4_out_V_V_full_n),
    .if_write(ResizeStream_U0_out_V_V_write),
    .if_dout(s4_out_V_V_dout),
    .if_empty_n(s4_out_V_V_empty_n),
    .if_read(Stream2Mem_U0_in_V_V_read)
);

start_for_Conv1DBmb6 start_for_Conv1DBmb6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Conv1DBuffer_new_U0_din),
    .if_full_n(start_for_Conv1DBuffer_new_U0_full_n),
    .if_write(ResizeStream_14_U0_start_write),
    .if_dout(start_for_Conv1DBuffer_new_U0_dout),
    .if_empty_n(start_for_Conv1DBuffer_new_U0_empty_n),
    .if_read(Conv1DBuffer_new_U0_ap_ready)
);

start_for_Stream2ncg start_for_Stream2ncg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Stream2Mem_U0_din),
    .if_full_n(start_for_Stream2Mem_U0_full_n),
    .if_write(ResizeStream_14_U0_start_write),
    .if_dout(start_for_Stream2Mem_U0_dout),
    .if_empty_n(start_for_Stream2Mem_U0_empty_n),
    .if_read(Stream2Mem_U0_ap_ready)
);

start_for_Conv1DMocq start_for_Conv1DMocq_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Conv1DMac_new_U0_din),
    .if_full_n(start_for_Conv1DMac_new_U0_full_n),
    .if_write(Conv1DBuffer_new_U0_start_write),
    .if_dout(start_for_Conv1DMac_new_U0_dout),
    .if_empty_n(start_for_Conv1DMac_new_U0_empty_n),
    .if_read(Conv1DMac_new_U0_ap_ready)
);

start_for_Relu1D7pcA start_for_Relu1D7pcA_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Relu1D77_U0_din),
    .if_full_n(start_for_Relu1D77_U0_full_n),
    .if_write(Conv1DMac_new_U0_start_write),
    .if_dout(start_for_Relu1D77_U0_dout),
    .if_empty_n(start_for_Relu1D77_U0_empty_n),
    .if_read(Relu1D77_U0_ap_ready)
);

start_for_StreamiqcK start_for_StreamiqcK_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_StreamingDataWidthCo_U0_din),
    .if_full_n(start_for_StreamingDataWidthCo_U0_full_n),
    .if_write(Relu1D77_U0_start_write),
    .if_dout(start_for_StreamingDataWidthCo_U0_dout),
    .if_empty_n(start_for_StreamingDataWidthCo_U0_empty_n),
    .if_read(StreamingDataWidthCo_U0_ap_ready)
);

start_for_Conv1DBrcU start_for_Conv1DBrcU_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Conv1DBuffer_new_1_U0_din),
    .if_full_n(start_for_Conv1DBuffer_new_1_U0_full_n),
    .if_write(StreamingDataWidthCo_U0_start_write),
    .if_dout(start_for_Conv1DBuffer_new_1_U0_dout),
    .if_empty_n(start_for_Conv1DBuffer_new_1_U0_empty_n),
    .if_read(Conv1DBuffer_new_1_U0_ap_ready)
);

start_for_Conv1DMsc4 start_for_Conv1DMsc4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Conv1DMac_new_1_U0_din),
    .if_full_n(start_for_Conv1DMac_new_1_U0_full_n),
    .if_write(Conv1DBuffer_new_1_U0_start_write),
    .if_dout(start_for_Conv1DMac_new_1_U0_dout),
    .if_empty_n(start_for_Conv1DMac_new_1_U0_empty_n),
    .if_read(Conv1DMac_new_1_U0_ap_ready)
);

start_for_Relu1D_U0 start_for_Relu1D_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Relu1D_U0_din),
    .if_full_n(start_for_Relu1D_U0_full_n),
    .if_write(Conv1DMac_new_1_U0_start_write),
    .if_dout(start_for_Relu1D_U0_dout),
    .if_empty_n(start_for_Relu1D_U0_empty_n),
    .if_read(Relu1D_U0_ap_ready)
);

start_for_Streamitde start_for_Streamitde_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_StreamingDataWidthCo_1_U0_din),
    .if_full_n(start_for_StreamingDataWidthCo_1_U0_full_n),
    .if_write(Relu1D_U0_start_write),
    .if_dout(start_for_StreamingDataWidthCo_1_U0_dout),
    .if_empty_n(start_for_StreamingDataWidthCo_1_U0_empty_n),
    .if_read(StreamingDataWidthCo_1_U0_ap_ready)
);

start_for_ResizeSudo start_for_ResizeSudo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_ResizeStream_U0_din),
    .if_full_n(start_for_ResizeStream_U0_full_n),
    .if_write(StreamingDataWidthCo_1_U0_start_write),
    .if_dout(start_for_ResizeStream_U0_dout),
    .if_empty_n(start_for_ResizeStream_U0_empty_n),
    .if_read(ResizeStream_U0_ap_ready)
);

assign Conv1DBuffer_new_1_U0_ap_continue = 1'b1;

assign Conv1DBuffer_new_1_U0_ap_start = start_for_Conv1DBuffer_new_1_U0_empty_n;

assign Conv1DBuffer_new_U0_ap_continue = 1'b1;

assign Conv1DBuffer_new_U0_ap_start = start_for_Conv1DBuffer_new_U0_empty_n;

assign Conv1DMac_new_1_U0_ap_continue = 1'b1;

assign Conv1DMac_new_1_U0_ap_start = start_for_Conv1DMac_new_1_U0_empty_n;

assign Conv1DMac_new_U0_ap_continue = 1'b1;

assign Conv1DMac_new_U0_ap_start = start_for_Conv1DMac_new_U0_empty_n;

assign Relu1D77_U0_ap_continue = 1'b1;

assign Relu1D77_U0_ap_start = start_for_Relu1D77_U0_empty_n;

assign Relu1D_U0_ap_continue = 1'b1;

assign Relu1D_U0_ap_start = start_for_Relu1D_U0_empty_n;

assign ResizeStream_14_U0_ap_continue = 1'b1;

assign ResizeStream_14_U0_ap_start = ap_start;

assign ResizeStream_14_U0_start_full_n = (start_for_Stream2Mem_U0_full_n & start_for_Conv1DBuffer_new_U0_full_n);

assign ResizeStream_U0_ap_continue = 1'b1;

assign ResizeStream_U0_ap_start = start_for_ResizeStream_U0_empty_n;

assign ResizeStream_U0_start_full_n = 1'b1;

assign ResizeStream_U0_start_write = 1'b0;

assign Stream2Mem_U0_ap_continue = 1'b1;

assign Stream2Mem_U0_ap_start = start_for_Stream2Mem_U0_empty_n;

assign Stream2Mem_U0_start_full_n = 1'b1;

assign Stream2Mem_U0_start_write = 1'b0;

assign StreamingDataWidthCo_1_U0_ap_continue = 1'b1;

assign StreamingDataWidthCo_1_U0_ap_start = start_for_StreamingDataWidthCo_1_U0_empty_n;

assign StreamingDataWidthCo_U0_ap_continue = 1'b1;

assign StreamingDataWidthCo_U0_ap_start = start_for_StreamingDataWidthCo_U0_empty_n;

assign ap_done = Stream2Mem_U0_ap_done;

assign ap_idle = (StreamingDataWidthCo_U0_ap_idle & StreamingDataWidthCo_1_U0_ap_idle & Stream2Mem_U0_ap_idle & ResizeStream_U0_ap_idle & ResizeStream_14_U0_ap_idle & Relu1D_U0_ap_idle & Relu1D77_U0_ap_idle & Conv1DMac_new_U0_ap_idle & Conv1DMac_new_1_U0_ap_idle & Conv1DBuffer_new_U0_ap_idle & Conv1DBuffer_new_1_U0_ap_idle);

assign ap_ready = ResizeStream_14_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Stream2Mem_U0_ap_done;

assign ap_sync_ready = ResizeStream_14_U0_ap_ready;

assign input1_V_V_TREADY = ResizeStream_14_U0_in_V_V_TREADY;

assign start_for_Conv1DBuffer_new_1_U0_din = 1'b1;

assign start_for_Conv1DBuffer_new_U0_din = 1'b1;

assign start_for_Conv1DMac_new_1_U0_din = 1'b1;

assign start_for_Conv1DMac_new_U0_din = 1'b1;

assign start_for_Relu1D77_U0_din = 1'b1;

assign start_for_Relu1D_U0_din = 1'b1;

assign start_for_ResizeStream_U0_din = 1'b1;

assign start_for_Stream2Mem_U0_din = 1'b1;

assign start_for_StreamingDataWidthCo_1_U0_din = 1'b1;

assign start_for_StreamingDataWidthCo_U0_din = 1'b1;

endmodule //computeS4
